import type { PageFaq } from "./types";

/**
 * Eight FAQs per feature module (/features/[slug]). Every answer is drawn from
 * lib/content.ts (modules, trial line), lib/featurePages.ts and lib/appFeatures.ts.
 */
export const featureFaqs: Record<string, PageFaq[]> = {
  attendance: [
    { q: "Which biometric devices does HRMagix attendance sync with?", a: "Attendance syncs through a biometric push API with eSSL, Matrix and ZKTeco devices." },
    { q: "Can remote employees mark attendance from their phones?", a: "Yes. The iOS and Android apps support GPS geo-fencing with selfie validation, so remote staff can punch in from their phones." },
    { q: "Does it handle rotating and night shifts?", a: "Yes. It automates shift rotation and applies night shift differentials." },
    { q: "Can I set a grace period for late arrivals?", a: "Yes. Late grace periods are configured as part of the shift rules." },
    { q: "How does attendance affect loss of pay in payroll?", a: "Loss-of-pay (LOP) is calculated automatically from attendance and fed straight into the monthly payroll run." },
    { q: "Where does attendance sit in the HRMagix app?", a: "It lives in the Time & Work area, where employees clock in and out and each session and the time worked are recorded." },
    { q: "Can employees see their own attendance history?", a: "Yes. The dashboard shows today's hours, each session, and hours worked over the last seven days with the total, daily average and days active." },
    { q: "Is attendance included in the free trial?", a: "Yes. The 14-day free trial gives full access to all 12 modules, attendance included." },
  ],
  leaves: [
    { q: "What leave types can I configure in HRMagix?", a: "You can create custom leave categories such as Earned/Privilege, Sick, and Maternity/Paternity leave." },
    { q: "Does HRMagix support multi-level leave approvals?", a: "Yes. Leave requests can go through multi-level manager and HR approval, with instant email and push alerts." },
    { q: "Are leave balances accrued automatically?", a: "Yes. Monthly accruals run automatically, along with carry-over rules." },
    { q: "Can HRMagix enforce the sandwich rule on leave?", a: "Yes. Sandwich-rule policies are enforced automatically." },
    { q: "Does it track compensatory offs?", a: "Yes. Compensatory-off tracking is part of the leave module." },
    { q: "How are holidays handled across different Indian states?", a: "HRMagix keeps unified visual holiday calendars across Indian states, and the company holiday list sits in the Time & Work area." },
    { q: "Are the leave quotas legally compliant?", a: "Leave quotas are built to comply with the Factories Act and the Shops and Establishments Act." },
    { q: "Can employees check their own leave balance?", a: "Yes. The dashboard shows the leave balance by type for the year, used against total, plus any pending leave requests." },
  ],
  payroll: [
    { q: "How long does a payroll run take in HRMagix?", a: "A complete monthly payroll can be executed in under 3 minutes." },
    { q: "Does HRMagix calculate EPF and ESI automatically?", a: "Yes. EPF is calculated with the 12% wage ceiling and ESI with the ₹21,000 threshold, automatically." },
    { q: "Is Professional Tax handled for multiple states?", a: "Yes. Multi-state Professional Tax is calculated automatically." },
    { q: "How does HRMagix handle TDS on salary?", a: "It compares the dual tax regimes under Section 192 and exports quarterly Form 24Q." },
    { q: "Can I generate bank transfer files for salaries?", a: "Yes. One click generates bank payment batch files formatted for NEFT, RTGS or IMPS." },
    { q: "Does it produce ECR files for EPFO and ESIC?", a: "Yes. It creates electronic challan receipt (ECR) files for the EPFO and ESIC portals." },
    { q: "Does attendance feed into payroll?", a: "Yes. Loss-of-pay is auto-calculated from attendance and fed into the monthly payroll." },
    { q: "Where is payroll in the HRMagix app?", a: "Payroll has its own area in the app's main navigation, covering the monthly run from salary structure to payslip." },
  ],
  okrs: [
    { q: "Can OKRs cascade from leadership to individuals?", a: "Yes. OKRs cascade from leadership down to individual contributors." },
    { q: "Does HRMagix support quarterly and annual OKR cycles?", a: "Yes. Both quarterly and annual OKRs are supported." },
    { q: "How is progress on key results tracked?", a: "Through real-time progress sliders with milestone weighting." },
    { q: "Can owners record confidence on their OKRs?", a: "Yes. OKRs carry confidence scores alongside their progress." },
    { q: "Does it remind teams to check in on OKRs?", a: "Yes. It sends sprint check-in reminders and automated bi-weekly health updates." },
    { q: "How do OKRs relate to KRAs in HRMagix?", a: "Both sit in the Performance area of the app: KRAs are key result areas for each role, while OKRs are objectives and key results." },
    { q: "What else is in the Performance area?", a: "Alongside OKRs, the Performance area holds KRA, Reviews, Skills and PIPs." },
    { q: "How do OKRs connect company goals to team sprints?", a: "OKRs align company vision with team sprints through transparent, quantitative Objective and Key Result hierarchies, backed by sprint check-in reminders." },
  ],
  "kra-9box": [
    { q: "What is a 9-box talent matrix in HRMagix?", a: "It is an interactive matrix that plots each employee's performance against their growth potential." },
    { q: "Can KRAs be defined per role?", a: "Yes. You define structured, role-specific Key Result Areas." },
    { q: "Does HRMagix support multi-rater evaluations?", a: "Yes. Role-based competency scoring matrices support multi-rater evaluations." },
    { q: "How does calibration work?", a: "Transparent calibration dashboards support executive leadership reviews." },
    { q: "Can the 9-box help identify future leaders?", a: "Yes. It is designed to visualise high-potential future leadership on an interactive talent matrix." },
    { q: "Where are KRAs found in the app?", a: "KRA sits in the Performance area of the app, alongside OKRs, Reviews, Skills and PIPs." },
    { q: "How does the 9-box connect to succession planning?", a: "The 9-box highlights high-potential employees, and the Succession module builds benches of successors with readiness ratings and development plans." },
    { q: "Does HRMagix also run performance reviews?", a: "Yes. Reviews sit in the Performance area of the app, alongside KRA, OKRs, Skills and PIPs." },
  ],
  pips: [
    { q: "What length of PIP does HRMagix support?", a: "HRMagix supports 30, 60 and 90-day Performance Improvement Plans." },
    { q: "How are PIP milestones tracked?", a: "Through structured milestone checkpoints with measurable turnaround criteria." },
    { q: "Can managers keep private notes during a PIP?", a: "Yes. There is a confidential manager-employee journal for objective documentation." },
    { q: "What happens when a PIP deadline is reached?", a: "Timeline escalations are automated, and the outcome status is signed off at the end." },
    { q: "Is a PIP in HRMagix only a disciplinary tool?", a: "No. The module is built for constructive plans, pairing milestone tracking with manager coaching logs." },
    { q: "Where are PIPs in the app?", a: "PIPs sit in the Performance area, next to KRA, OKRs, Reviews and Skills." },
    { q: "Can 1-on-1s be used alongside a PIP?", a: "Yes. The 1-on-1s & Meetings module lets managers run recurring conversations with shared agendas and tracked action items." },
    { q: "Which other modules sit in the Performance group?", a: "PIPs & Growth sits in the Performance group with Objectives & OKRs and KRA & 9-Box." },
  ],
  recognition: [
    { q: "How do employees recognise each other in HRMagix?", a: "Through peer-to-peer kudos tied to your company's core values badges." },
    { q: "Can badges reflect our company values?", a: "Yes. Badges are customised to your company's core values." },
    { q: "What is the culture wall?", a: "A live, interactive culture feed of recognition, embedded directly in employees' home dashboards." },
    { q: "Is there a recognition leaderboard?", a: "Yes. There is a monthly recognition leaderboard." },
    { q: "Can recognition come with rewards?", a: "Yes. The module includes spot reward allowance redemption." },
    { q: "What are growth points?", a: "Growth points are earned over time, with an all-time balance shown on every dashboard." },
    { q: "Where does recognition sit in the app?", a: "In the Engagement area, alongside Meetings, Growth & Points, Wellness and Speak Up." },
    { q: "Does HRMagix also support manager 1-on-1s?", a: "Yes. The 1-on-1s & Meetings module sits in the same Engagement group, with shared agendas and tracked action items." },
  ],
  meetings: [
    { q: "Can managers and employees share a 1-on-1 agenda?", a: "Yes. Pre-meeting agendas are collaborative, with continuous talking points." },
    { q: "Are action items from meetings tracked?", a: "Yes. Action items can be assigned, with automated due-date reminders." },
    { q: "Can managers keep private coaching notes?", a: "Yes. Managers can keep private coaching notes." },
    { q: "Is there a history of past 1-on-1s?", a: "Yes. Historical conversation archives are kept." },
    { q: "Does it support recurring meetings?", a: "Yes. It is built for managers holding recurring coaching conversations." },
    { q: "Where are meetings in the HRMagix app?", a: "Meetings, including 1-on-1s, sit in the Engagement area of the app." },
    { q: "How do 1-on-1s relate to performance improvement plans?", a: "The PIPs & Growth module pairs 30/60/90-day plans with manager coaching logs, while 1-on-1s give managers recurring coaching conversations with shared agendas." },
    { q: "Which other Engagement module works alongside 1-on-1s?", a: "Recognition sits in the same Engagement group, with peer kudos, values badges and a live culture wall." },
  ],
  onboarding: [
    { q: "Can new hires submit documents before day one?", a: "Yes. A self-service pre-boarding portal lets them upload PAN, Aadhaar and bank documents." },
    { q: "Does HRMagix generate appointment letters?", a: "Yes. Appointment letters are generated automatically, with digital signature capability." },
    { q: "Can IT and workspace setup be tracked?", a: "Yes. There is a checklist for tracking IT hardware and workspace asset provisioning." },
    { q: "Is onboarding paperless?", a: "Yes. Documents are collected digitally, with structured department welcome workflows." },
    { q: "Where is onboarding in the app?", a: "Onboarding sits in the People area, alongside Memos, Documents and Assets." },
    { q: "Where are employee documents stored after joining?", a: "The Documents module keeps a centralised, encrypted repository with role-based access control." },
    { q: "Can company assets be found later?", a: "Yes. Company assets sit in the People area and are searchable from the global search." },
    { q: "Which module group does Onboarding belong to?", a: "Onboarding is part of the People group, alongside Documents and Succession." },
  ],
  documents: [
    { q: "How are employee documents secured in HRMagix?", a: "Personnel files are encrypted, and access is set by role." },
    { q: "Can I track who has signed the handbook or an NDA?", a: "Yes. The module tracks sign-off on the company handbook, NDAs and compliance policies." },
    { q: "Does HRMagix alert me before documents expire?", a: "Yes. Automated alerts cover visa, driving licence and certificate expiry." },
    { q: "Are all documents kept in one place?", a: "Yes. It is a centralised repository for employee and company documents." },
    { q: "Where are documents in the app?", a: "Documents sit in the People area, alongside Memos, Assets and Onboarding." },
    { q: "Can policy acknowledgments be tracked?", a: "Yes. Policy acknowledgment tracking is built in." },
    { q: "Where can employees see company policies?", a: "The Time & Work area includes All Policies, listing every company policy." },
    { q: "How do Documents connect to Onboarding?", a: "Both sit in the People area: Onboarding collects PAN, Aadhaar and bank documents through a pre-boarding portal, and Documents is the repository for employee and company documents." },
  ],
  succession: [
    { q: "How does HRMagix identify critical roles?", a: "Through a key position vulnerability index and role criticality assessment." },
    { q: "What readiness ratings are used for successors?", a: "Successors are rated Ready now, 1-2 years, or 3+ years." },
    { q: "Can I create development plans for successors?", a: "Yes. Targeted individual development plans (IDPs) can be set for high-potential successors." },
    { q: "What is the goal of succession planning in HRMagix?", a: "To identify critical single-point-of-failure roles and build internal leadership benches for future growth." },
    { q: "Can succession use performance data?", a: "The KRA & 9-Box module plots performance against potential, helping spot the high-potential people who form a bench." },
    { q: "Which group does Succession belong to?", a: "Succession is part of the People group of modules, with Onboarding and Documents." },
    { q: "Is succession planning focused on leadership roles?", a: "Yes. It builds internal leadership candidate benches for critical roles, to support future growth." },
    { q: "What is a single-point-of-failure role?", a: "A critical role the Succession module helps you identify, so an internal leadership bench can be built for it." },
  ],
  analytics: [
    { q: "What workforce metrics does HRMagix Analytics show?", a: "Real-time headcount growth, department distributions and gender diversity." },
    { q: "Does Analytics flag attrition risk?", a: "Yes. It provides early warning attrition risk indicators alongside tenure analysis." },
    { q: "Can I track overtime costs?", a: "Yes. Analytics reports overtime expenses." },
    { q: "Does it show leave utilisation?", a: "Yes. Leave utilisation rates are included." },
    { q: "Can I compare payroll against budget?", a: "Yes. Analytics tracks payroll budget variance." },
    { q: "Is the data real-time?", a: "Yes. Workforce trends are shown in real time." },
    { q: "Who is Analytics designed for?", a: "It turns people data into clear reports for leadership on workforce trends, attrition and payroll costs." },
    { q: "Does Analytics report on gender diversity?", a: "Yes. Gender diversity is shown in real time alongside headcount growth and department distributions." },
  ],
};
