import type { PageFaq } from "./types";

/**
 * Page FAQs for /resources/glossary/[slug], keyed by the term's slug
 * (slugify(term.term)). Every answer restates what lib/glossary.ts already
 * defines, for this term or a related one; nothing here adds a rate,
 * threshold or product claim that the glossary does not already make.
 */
export const glossaryFaqs: Record<string, PageFaq[]> = {
  arrears: [
    { q: "What are arrears in salary?", a: "Arrears are pay owed for an earlier period and settled in a later one, most often because an increment was agreed after its effective date." },
    { q: "Why do salary arrears arise?", a: "The most common cause is an increment agreed after the date it is meant to apply from, so the months in between were paid at the old salary." },
    { q: "How are arrears calculated?", a: "The affected months are recomputed under the revised salary and the difference is worked out for each of them." },
    { q: "How do arrears appear on a payslip?", a: "The difference is paid as an identified line in the current month's payslip rather than being folded into ordinary pay." },
    { q: "Are old payslips reissued when arrears are paid?", a: "No. The original payslips stand as issued, because they were right under the salary in force at the time." },
    { q: "What is the difference between arrears and a payroll correction?", a: "An arrear says the earlier payslip was right under the salary then in force; a correction says the earlier payslip was wrong." },
    { q: "How does effective dating relate to arrears?", a: "Effective dating records the date a salary revision applies from, which is what tells payroll which past months need to be recomputed." },
    { q: "Why are arrears paid as a separate line?", a: "So the difference is identified in the current month while the original payslips stand as issued." },
  ],
  attrition: [
    { q: "What does attrition mean in HR?", a: "Attrition is the rate at which employees leave an organisation over a period." },
    { q: "Is a single company-wide attrition rate useful?", a: "Read on its own it says little. Its value comes from breaking it down." },
    { q: "How should attrition be analysed?", a: "By department, tenure band or grade, which usually shows where departures are actually concentrated." },
    { q: "Why break attrition down by department?", a: "What feels like a company-wide problem is often concentrated in one team, and a single figure hides that." },
    { q: "How does tenure relate to attrition?", a: "Reading attrition by tenure band shows whether people are leaving early or late in their service, which an overall rate cannot show." },
    { q: "Why is attrition measured over a period?", a: "It is a rate of leaving, so it only means something against a defined time window." },
    { q: "Is attrition the same as tenure?", a: "No. Tenure is how long someone has been employed; attrition is the rate at which people leave." },
    { q: "What should I do when attrition feels high everywhere?", a: "Cut the figure by department, tenure and grade before acting; the problem is usually concentrated in one place." },
  ],
  "basic-pay": [
    { q: "What is basic pay?", a: "Basic pay is the core fixed component of a salary, before allowances." },
    { q: "Why does basic pay matter so much?", a: "The provident fund wage and the gratuity calculation are both computed on it, so it drives costs well beyond its own size." },
    { q: "Is PF calculated on basic pay?", a: "Yes. The PF wage is basic plus dearness allowance, subject to the ₹15,000 statutory ceiling where the employer applies it." },
    { q: "Is gratuity calculated on basic pay?", a: "Yes. Gratuity uses the last drawn basic, at fifteen days' wages for each completed year on a twenty-six day divisor." },
    { q: "Is the split between basic and allowances just formatting?", a: "No. Because PF and gratuity depend on basic, the split is a cost decision rather than a formatting one." },
    { q: "Is basic pay the same as gross salary?", a: "No. Gross salary is basic plus allowances and any variable components, before deductions." },
    { q: "Does dearness allowance count with basic pay?", a: "Where DA is paid, it forms part of the PF wage together with basic and part of the wages used for gratuity." },
    { q: "Is basic pay fixed or variable?", a: "It is the fixed core of the salary; variable components sit outside it in gross." },
  ],
  calibration: [
    { q: "What is calibration in performance reviews?", a: "Calibration is the step where draft ratings are compared across managers before they are finalised." },
    { q: "Why is calibration needed?", a: "Two managers assessing comparable work rarely arrive at the same rating unaided." },
    { q: "When does calibration happen in a review cycle?", a: "After managers produce draft ratings and before those ratings are finalised." },
    { q: "Does calibration change ratings?", a: "It can. The point of comparing drafts across managers is to align ratings for comparable work before they become final." },
    { q: "Who takes part in calibration?", a: "The managers whose draft ratings are being compared against one another." },
    { q: "How does a 9-box relate to calibration?", a: "A 9-box plots performance against potential and is comparative by nature, which makes it useful when looking across a team rather than at one person." },
    { q: "Is calibration the same as a performance review?", a: "No. It is one step within the review cycle, focused on consistency of ratings across managers." },
    { q: "Where does HRMagix cover calibration?", a: "It sits within the Performance & OKRs solution." },
  ],
  "comp-off": [
    { q: "What is comp-off?", a: "Compensatory off is leave earned by working on a non-working day, a weekly off or a public holiday, granted instead of an overtime premium." },
    { q: "How is comp-off earned?", a: "By working on a day that was not a working day. It is a consequence of the attendance record, not a discretionary grant." },
    { q: "Is comp-off paid instead of overtime?", a: "Yes. It is granted instead of paying an overtime premium for the day worked." },
    { q: "Does comp-off expire?", a: "It normally does. It lapses if unused by the date the employer's policy sets." },
    { q: "Can an employee apply for comp-off from a leave balance?", a: "Not like an ordinary leave type. It has to be earned first by working a non-working day." },
    { q: "Does working on a public holiday earn comp-off?", a: "Working on a public holiday is one of the ways comp-off is earned, alongside weekly offs and other non-working days." },
    { q: "Why is comp-off tied to attendance records?", a: "Because it is earned by the day actually worked, the attendance record is what establishes entitlement." },
    { q: "Who decides how long comp-off stays valid?", a: "The employer's leave policy sets the expiry date." },
  ],
  "continuous-service": [
    { q: "What is continuous service?", a: "Unbroken service with the same employer, counted from the date of joining." },
    { q: "Why does continuous service matter for gratuity?", a: "It is the qualifying test: gratuity is payable after five years of continuous service." },
    { q: "Does continuous service affect leave?", a: "Yes. It underlies leave accrual as well as gratuity eligibility." },
    { q: "Does an internal transfer break continuous service?", a: "It should not. A transfer should be a dated change on the existing record rather than a new record." },
    { q: "Why shouldn't a transfer create a new employee record?", a: "A new record would restart the service count, affecting gratuity eligibility and leave accrual." },
    { q: "From when is continuous service counted?", a: "From the date of joining the employer." },
    { q: "Is continuous service the same as tenure?", a: "Both start at the date of joining, but continuous service is the unbroken service that statutory tests such as gratuity rely on." },
    { q: "Is the five-year gratuity condition ever waived?", a: "Yes. It does not apply in the case of death or disablement." },
  ],
  "contribution-period": [
    { q: "What is the ESI contribution period?", a: "A fixed half-yearly window over which ESI eligibility is determined." },
    { q: "Is ESI eligibility checked every month?", a: "No. It is determined for the contribution period, not month by month." },
    { q: "What happens if salary crosses the ESI threshold mid-period?", a: "An employee covered at the start of the period stays covered for its duration, even if a revision takes gross above the threshold." },
    { q: "How long is an ESI contribution period?", a: "It is half-yearly." },
    { q: "What is the most common ESI eligibility mistake?", a: "Treating eligibility as a monthly test, which is among the most common and most expensive payroll errors in India." },
    { q: "What is the current ESI wage threshold?", a: "₹21,000 gross a month." },
    { q: "Do ESI deductions stop after an increment?", a: "Not within the same contribution period if the employee was covered at its start." },
    { q: "Where can I calculate ESI contributions?", a: "The ESI calculator applies the employee and employer rates to gross." },
  ],
  ctc: [
    { q: "What is CTC?", a: "Cost to company: the employer's total annual cost of employing someone, gross pay plus the employer's contributions and other attributed costs." },
    { q: "Is CTC the same as salary?", a: "No. It is frequently quoted as salary, but it is what the employer spends, not what the employee receives." },
    { q: "What is the difference between CTC and gross salary?", a: "Gross is what is earned before deductions; CTC adds the employer's own contributions and other costs on top." },
    { q: "What is the difference between CTC and take-home?", a: "Take-home is what reaches the bank after deductions; CTC is the employer's full cost, which is always higher." },
    { q: "Why is CTC higher than gross?", a: "Because it includes the employer's own contributions and other costs attributed to the role." },
    { q: "Does an employee ever receive their full CTC?", a: "No. CTC is never an amount the employee receives." },
    { q: "Is CTC annual or monthly?", a: "CTC is expressed as an annual figure." },
    { q: "How can I convert CTC to take-home?", a: "The salary calculator works from CTC through gross to take-home." },
  ],
  "dearness-allowance": [
    { q: "What is dearness allowance?", a: "A cost-of-living component paid alongside basic pay." },
    { q: "Is DA included in the PF wage?", a: "Yes. Where it is paid, DA forms part of the PF wage together with basic." },
    { q: "Is DA included in gratuity calculation?", a: "Yes. Where paid, it is part of the wages used in the gratuity calculation." },
    { q: "Is dearness allowance paid by every employer?", a: "No. The glossary describes its treatment where it is paid." },
    { q: "Is DA part of basic pay?", a: "It is a separate component paid alongside basic, but treated with basic for PF and gratuity." },
    { q: "Does DA affect PF contributions?", a: "Yes, because PF is computed on basic plus DA, subject to the ₹15,000 ceiling where applied." },
    { q: "What is the purpose of dearness allowance?", a: "It compensates for the cost of living." },
    { q: "Does DA count towards gross salary?", a: "Yes. Gross covers basic, allowances and variable components before deductions." },
  ],
  ecr: [
    { q: "What is ECR in EPF?", a: "Electronic Challan cum Return: the monthly return file uploaded to the EPFO portal." },
    { q: "What does an ECR file contain?", a: "Each member's wages and contributions for the month." },
    { q: "How often is ECR filed?", a: "Monthly." },
    { q: "Where is the ECR uploaded?", a: "To the EPFO portal." },
    { q: "Who should produce the ECR?", a: "Ideally the payroll run that computed the contributions, rather than a separately assembled file." },
    { q: "Why shouldn't ECR be prepared separately from payroll?", a: "A separately assembled file can drift from the contributions payroll actually computed." },
    { q: "What wage is reported in the ECR?", a: "The PF wage, basic plus DA subject to the ₹15,000 ceiling where the employer applies it, on which contributions are computed." },
    { q: "Does the ECR need correct UANs?", a: "Each member is identified in it, and UAN is one of the identifiers that must be correct before the first payroll run." },
  ],
  "effective-dating": [
    { q: "What is effective dating in HR systems?", a: "Recording when a change takes effect, not just that it happened, so a past period can be read as it stood at the time." },
    { q: "Which changes should be effective dated?", a: "Salary revisions, policy changes and reporting-line moves should all carry the date they apply from." },
    { q: "Is effective dating the same as an audit log?", a: "No. Effective dating changes what the system calculates for a period; an audit log only records who typed what." },
    { q: "Why does effective dating matter for payroll?", a: "It lets payroll compute each period under the terms in force then, for example when an increment is backdated and arrears are due." },
    { q: "How does effective dating help with transfers?", a: "A transfer becomes a dated change on the existing record, which keeps continuous service intact." },
    { q: "Can I view a past period as it was with effective dating?", a: "Yes. That is its purpose: reading a past period as it stood at the time." },
    { q: "What happens without effective dating?", a: "The system only knows the current value, so past periods can't be reconstructed or recomputed correctly." },
    { q: "Does effective dating replace history?", a: "No. It records when changes apply; the history of who made edits is a separate audit record." },
  ],
  epf: [
    { q: "What is EPF?", a: "The Employees' Provident Fund, a statutory retirement savings scheme." },
    { q: "What is the EPF contribution rate?", a: "The employee contributes 12% of the PF wage and the employer 12%." },
    { q: "How is the employer's EPF share split?", a: "Of the employer's 12%, 8.33% is diverted to the pension scheme within the statutory ceiling." },
    { q: "When does EPF coverage apply?", a: "Generally from twenty employees in a covered establishment." },
    { q: "Can a smaller company join EPF voluntarily?", a: "Yes. Voluntary coverage is possible below twenty employees." },
    { q: "On what wage is EPF calculated?", a: "On the PF wage: basic plus dearness allowance, subject to the ₹15,000 ceiling where the employer applies it." },
    { q: "How is EPF reported each month?", a: "Through the ECR file uploaded to the EPFO portal, carrying each member's wages and contributions." },
    { q: "What identifies an EPF member across jobs?", a: "The UAN, which stays with the individual across employers." },
  ],
  eps: [
    { q: "What is EPS?", a: "The Employees' Pension Scheme, funded from within the employer's provident fund contribution." },
    { q: "What is the EPS contribution rate?", a: "8.33%, taken from the employer's PF contribution, subject to the statutory wage ceiling." },
    { q: "Is EPS an extra cost over the employer's PF?", a: "No. It is a split of the employer's 12%, not an addition to it." },
    { q: "Does the employee contribute to EPS?", a: "No. EPS is funded from the employer's share." },
    { q: "Is EPS subject to a wage ceiling?", a: "Yes. The 8.33% applies within the statutory wage ceiling." },
    { q: "What is the difference between EPF and EPS?", a: "EPF is the provident fund scheme; EPS is the pension component carved out of the employer's EPF contribution." },
    { q: "Where does the rest of the employer's PF contribution go?", a: "What is not diverted to EPS remains in the provident fund." },
    { q: "Why doesn't all of the employer's PF go to the provident fund?", a: "Because 8.33% of the employer's 12% is diverted to the pension scheme, within the statutory ceiling." },
  ],
  esi: [
    { q: "What is ESI?", a: "Employees' State Insurance, a contributory health and social security scheme." },
    { q: "Who is eligible for ESI?", a: "Employees earning at or below the wage threshold, currently ₹21,000 gross a month." },
    { q: "What are the ESI contribution rates?", a: "The employee contributes 0.75% of gross and the employer 3.25%." },
    { q: "When does ESI apply to an establishment?", a: "Coverage generally begins at ten employees in a covered establishment." },
    { q: "Is ESI calculated on basic or gross?", a: "On gross." },
    { q: "Is ESI eligibility checked monthly?", a: "No. It is determined over a half-yearly contribution period." },
    { q: "Does an increment stop ESI immediately?", a: "No. An employee covered at the start of a contribution period stays covered for that period." },
    { q: "Can loss of pay change ESI contributions?", a: "In some cases, because LOP reduces paid days and therefore the salary on which contributions are computed." },
  ],
  "form-16": [
    { q: "What is Form 16?", a: "The annual certificate an employer issues summarising salary paid and tax deducted at source for the financial year." },
    { q: "Who issues Form 16?", a: "The employer, to the employee." },
    { q: "What is in Part B of Form 16?", a: "The salary breakdown and the tax computation." },
    { q: "How often is Form 16 issued?", a: "Annually, for the financial year." },
    { q: "What if payroll changed systems mid-year?", a: "Form 16 must still reconcile across the whole year regardless of how many systems produced it." },
    { q: "How does Form 16 relate to TDS?", a: "It certifies the TDS on salary deducted under Section 192 during the year." },
    { q: "How does Form 16 relate to Form 24Q?", a: "Form 24Q reports salary TDS quarterly; Form 16 certifies the year's total to the employee." },
    { q: "Where can employees get their Form 16?", a: "Self-service gives employees access to their own Form 16 along with payslips." },
  ],
  "form-24q": [
    { q: "What is Form 24Q?", a: "The quarterly return through which an employer reports tax deducted at source on salary." },
    { q: "How often is Form 24Q filed?", a: "Quarterly." },
    { q: "Which section governs Form 24Q?", a: "Section 192 of the Income Tax Act, which covers TDS on salary." },
    { q: "What must Form 24Q reconcile to?", a: "The deductions the payroll runs actually made in the quarter." },
    { q: "What is the difference between Form 24Q and Form 16?", a: "Form 24Q is the employer's quarterly return; Form 16 is the annual certificate to the employee." },
    { q: "Does Form 24Q cover non-salary TDS?", a: "It is the return for tax deducted on salary under Section 192." },
    { q: "Why does Form 24Q depend on payroll?", a: "It reports the TDS that each payroll run deducted, so the two must agree." },
    { q: "How is salary TDS projected before filing 24Q?", a: "Across the financial year, against the employee's regime election and verified declarations." },
  ],
  "full-and-final-settlement": [
    { q: "What is full and final settlement?", a: "The closing payment when employment ends." },
    { q: "What is included in full and final settlement?", a: "Salary to the last working day, leave encashment, notice pay or recovery, gratuity where due, less advances and unreturned assets." },
    { q: "How is salary to the last working day worked out in F&F?", a: "From the attendance record." },
    { q: "Is leave encashment part of F&F?", a: "Yes. It is taken from the leave ledger." },
    { q: "How does the notice period affect F&F?", a: "Notice pay or a recovery is drawn from the resignation record." },
    { q: "Is gratuity paid in full and final settlement?", a: "Where the qualifying service is complete, generally five years of continuous service." },
    { q: "What can be deducted in F&F?", a: "Advances and unreturned assets." },
    { q: "Why is F&F hard to get right?", a: "It draws on every other record at once: attendance, leave, resignation, service and recoveries." },
  ],
  gratuity: [
    { q: "What is gratuity?", a: "A statutory payment on separation to employees who have completed five years of continuous service." },
    { q: "How is gratuity calculated?", a: "Fifteen days' wages for each completed year of service, on the last drawn basic, using a twenty-six day divisor." },
    { q: "How many years of service are needed for gratuity?", a: "Five years of continuous service." },
    { q: "Is gratuity payable before five years on death?", a: "Yes. The five-year condition does not apply in the case of death or disablement." },
    { q: "Which salary is used for gratuity?", a: "The last drawn basic, together with dearness allowance where it is paid." },
    { q: "Why is a 26-day divisor used for gratuity?", a: "It is the divisor the statutory formula uses to arrive at fifteen days' wages." },
    { q: "Is gratuity part of full and final settlement?", a: "Yes, where the qualifying service is complete." },
    { q: "Can I calculate gratuity online?", a: "The gratuity calculator applies the statutory formula to your own figures." },
  ],
  "gross-salary": [
    { q: "What is gross salary?", a: "Everything earned in a month before any deduction: basic, allowances and variable components." },
    { q: "Why is gross salary important?", a: "Statutory deductions and taxes are applied to it or to components within it, so most rules are anchored to it." },
    { q: "What is the difference between gross and CTC?", a: "CTC adds the employer's own contributions and other costs on top of gross." },
    { q: "What is the difference between gross and take-home?", a: "Take-home is gross less the employee's statutory contributions, TDS and other authorised deductions." },
    { q: "Is ESI calculated on gross salary?", a: "Yes. ESI rates are applied to gross, and eligibility uses a ₹21,000 gross monthly threshold." },
    { q: "Is PF calculated on gross salary?", a: "No. PF uses the PF wage, basic plus DA, not full gross." },
    { q: "Does gross salary include variable pay?", a: "Yes, any variable components earned in the month are included." },
    { q: "Is gross salary monthly?", a: "As defined here it is the monthly figure earned before deduction." },
  ],
  "grace-period": [
    { q: "What is a grace period in attendance?", a: "A short window after shift start within which arrival is not treated as late." },
    { q: "Is a grace period required by law?", a: "No. It is an employer policy, not a statutory concept." },
    { q: "Who sets the grace period?", a: "The employer, through its attendance policy." },
    { q: "Does the grace period affect behaviour?", a: "Its length is one of the few settings that visibly changes attendance behaviour." },
    { q: "Is a grace-period arrival marked late?", a: "No, arrival within the window is not treated as late." },
    { q: "How does grace period relate to shifts?", a: "It is measured from the start of the shift the employee is assigned." },
    { q: "What if an employee arrives after the grace period?", a: "The arrival is treated as late under the employer's policy; a genuine error can be corrected through regularisation." },
    { q: "Is grace period the same across companies?", a: "No. Since it is a policy choice, its length varies by employer." },
  ],
  hrms: [
    { q: "What is an HRMS?", a: "A Human Resource Management System holding one authoritative record per employee and running the workflows that read from it." },
    { q: "What does an HRMS cover?", a: "Workflows such as attendance, leave, payroll, performance and documents." },
    { q: "What is the defining feature of an HRMS?", a: "The single employee record, not the number of features." },
    { q: "Is HRMS the same as payroll software?", a: "No. Payroll is a calculation that reads the record; an HRMS is the record plus everything else that reads it." },
    { q: "Why does a single employee record matter?", a: "Every workflow reads the same data, so attendance, leave and payroll agree." },
    { q: "How do employees use an HRMS?", a: "Through self-service: payslips, Form 16, leave, attendance regularisation and declarations." },
    { q: "Does an HRMS handle performance?", a: "Performance is one of the workflows an HRMS runs from the record." },
    { q: "Where can I learn about HRMagix HRMS?", a: "On the HRMS solution page." },
  ],
  kra: [
    { q: "What is a KRA?", a: "A Key Result Area: an ongoing area of accountability attached to a role." },
    { q: "Do KRAs change every quarter?", a: "No. They are stable across quarters." },
    { q: "What is the difference between KRA and OKR?", a: "An OKR is time-bound and ambitious; a KRA is continuous and role-bound." },
    { q: "Should appraisals use KRAs or OKRs?", a: "Appraisals go wrong when an organisation measures only one of the two." },
    { q: "What does a KRA describe?", a: "What a person is responsible for by virtue of the job they hold." },
    { q: "Is a KRA a goal?", a: "Not a period goal; it describes ongoing responsibility rather than what someone is trying to change this period." },
    { q: "Who owns KRAs, the role or the person?", a: "They are attached to the role." },
    { q: "Do KRAs feed into performance reviews?", a: "Yes, alongside OKRs, as the continuous side of what is assessed." },
  ],
  lop: [
    { q: "What is LOP in salary?", a: "Loss of pay: an unpaid day." },
    { q: "When does LOP apply?", a: "For absence without an approved application, or leave taken against an exhausted balance." },
    { q: "How does LOP affect salary?", a: "It reduces paid days for the month, and therefore the salary." },
    { q: "Does LOP affect PF?", a: "Yes. Fewer paid days reduce the PF wage." },
    { q: "Does LOP affect ESI?", a: "In some cases it reduces the ESI contribution." },
    { q: "Is LOP a penalty?", a: "No. It is simply the withholding of pay for a day not worked and not covered by leave." },
    { q: "Can an LOP be reversed?", a: "If the day was actually worked, the attendance record can be corrected through regularisation." },
    { q: "Is leave taken against an exhausted balance LOP?", a: "Yes. Leave taken against an exhausted balance is one of the two ways an LOP day arises." },
  ],
  lwf: [
    { q: "What is LWF?", a: "The Labour Welfare Fund, a state-administered welfare fund operated in some states." },
    { q: "Who contributes to LWF?", a: "Both employer and employee have shares." },
    { q: "Does LWF apply in every state?", a: "No, only in some states." },
    { q: "How often is LWF paid?", a: "The periodicity is set by the state; half-yearly and annual cycles are both common." },
    { q: "Why is LWF tricky for multi-state employers?", a: "Deadlines and cycles differ by state." },
    { q: "Who sets LWF amounts?", a: "The state that administers the fund." },
    { q: "Is LWF a central scheme like EPF?", a: "No. It is state-administered." },
    { q: "Is LWF the same as professional tax?", a: "No. Both are state-level, but LWF is a welfare fund while professional tax is a tax on employment." },
  ],
  "maternity-benefit": [
    { q: "What is maternity benefit?", a: "Paid leave and associated protections under the Maternity Benefit Act." },
    { q: "Is maternity leave a company policy?", a: "No. It is a statutory entitlement." },
    { q: "Does maternity leave reduce the ordinary leave balance?", a: "No. It is tracked as its own leave type and does not draw on the ordinary leave pool." },
    { q: "Which law governs maternity benefit in India?", a: "The Maternity Benefit Act." },
    { q: "Is maternity leave paid?", a: "Yes, it provides paid leave." },
    { q: "Does maternity benefit include more than leave?", a: "Yes. The Act provides associated protections alongside paid leave." },
    { q: "How should an HRMS record maternity leave?", a: "As a separate leave type, since it is a statutory entitlement." },
    { q: "Where is leave management covered?", a: "In HRMagix's Leave Management solution." },
  ],
  "muster-roll": [
    { q: "What is a muster roll?", a: "The attendance register an establishment is required to maintain." },
    { q: "Can a muster roll be digital?", a: "Yes. It can be kept on paper or digitally." },
    { q: "What does an inspection check in a muster roll?", a: "A specific question about a specific person on a specific date." },
    { q: "Is maintaining a muster roll mandatory?", a: "Yes, it is a register an establishment is required to maintain." },
    { q: "How is a muster roll different from a wage register?", a: "The muster roll records attendance; the wage register records wages paid." },
    { q: "Why do corrections matter in a muster roll?", a: "Regularisation keeps the original capture beside the correction, so the record remains evidence." },
    { q: "Are totals enough for a muster roll?", a: "No. It must answer for a specific person and date." },
    { q: "Where does the muster roll data come from?", a: "From the attendance record measured against shifts." },
  ],
  "new-tax-regime": [
    { q: "What is the new tax regime?", a: "An alternative personal income tax structure with different slab rates and far fewer exemptions and deductions than the old regime." },
    { q: "Who chooses the tax regime?", a: "The employee; the election belongs to them." },
    { q: "How does the regime choice affect TDS?", a: "It drives the employee's TDS for the year." },
    { q: "Is the new tax regime always better?", a: "No. It depends on the individual's declarations." },
    { q: "Can two people with the same salary benefit from different regimes?", a: "Yes. The answer differs between two people on identical salaries." },
    { q: "How should I compare old and new tax regimes?", a: "On your own numbers, including your declarations." },
    { q: "Does the new regime allow deductions?", a: "Substantially fewer than the old regime." },
    { q: "How does payroll use the regime election?", a: "Under Section 192, TDS is projected across the year against the regime election and verified declarations." },
  ],
  "notice-period": [
    { q: "What is a notice period?", a: "The period a party must serve after resignation or termination." },
    { q: "Who sets the notice period?", a: "The employment contract." },
    { q: "Can a notice period be bought out?", a: "In some cases, by agreement." },
    { q: "Does the notice period interact with leave?", a: "Yes, it interacts with leave and with the last working day." },
    { q: "Does the notice period apply to termination too?", a: "Yes. It applies after resignation or termination." },
    { q: "How does notice period affect full and final settlement?", a: "F&F includes notice pay or recovery from the resignation record." },
    { q: "Is the notice period fixed by law?", a: "As defined here, it is set by the employment contract." },
    { q: "How is the last working day decided?", a: "By the notice period served, together with any leave or buyout agreed." },
  ],
  "9-box": [
    { q: "What is a 9-box grid?", a: "A three-by-three matrix plotting demonstrated performance against assessed potential." },
    { q: "What are the axes of a 9-box?", a: "Performance and potential." },
    { q: "What is a 9-box used for?", a: "Comparison: it shows where a team is dense and where it is thin." },
    { q: "Does a 9-box position say much about one person?", a: "Very little, read alone." },
    { q: "Is performance the same as potential in a 9-box?", a: "No. Performance is demonstrated; potential is assessed." },
    { q: "How does a 9-box fit with calibration?", a: "Both are comparative, looking across people rather than at one in isolation." },
    { q: "How many boxes does a 9-box have?", a: "Nine, from a three-by-three grid." },
    { q: "What is the common mistake with a 9-box?", a: "Reading a single person's position alone rather than the team's distribution." },
  ],
  okr: [
    { q: "What is an OKR?", a: "An Objective and Key Result: a qualitative objective paired with quantitative key results." },
    { q: "How should an objective be written?", a: "To be memorable." },
    { q: "What are key results?", a: "Quantitative measures of progress toward the objective, meant to be read rather than argued about." },
    { q: "What is the difference between OKR and KRA?", a: "OKRs are time-bound and ambitious; KRAs are continuous and role-bound." },
    { q: "Are OKRs time-bound?", a: "Yes." },
    { q: "Should OKRs replace KRAs?", a: "No. Appraisals go wrong when only one of the two is measured." },
    { q: "Are key results qualitative?", a: "No. The objective is qualitative; key results are quantitative." },
    { q: "Does HRMagix support OKRs?", a: "Yes, through the Performance & OKRs solution." },
  ],
  payslip: [
    { q: "What is a payslip?", a: "The statement issued for a pay period, showing earnings, deductions and net pay." },
    { q: "What does a payslip show?", a: "Earnings, deductions and net pay." },
    { q: "Should a reissued payslip be regenerated?", a: "No. It should be the original document, since the period has already been filed against." },
    { q: "How do arrears appear on a payslip?", a: "As an identified line in the current month; earlier payslips stand as issued." },
    { q: "What is net pay on a payslip?", a: "Take-home: gross less statutory contributions, TDS and other authorised deductions." },
    { q: "Where can employees download payslips?", a: "Through employee self-service." },
    { q: "How do I read an Indian payslip?", a: "The blog post on reading an Indian payslip walks through it." },
    { q: "Does a payslip show TDS?", a: "Yes, tax deducted at source is among the deductions." },
  ],
  "pf-wage": [
    { q: "What is PF wage?", a: "The wage base for provident fund contributions: basic plus dearness allowance." },
    { q: "What is the PF wage ceiling?", a: "₹15,000, where the employer applies it." },
    { q: "Is the PF wage the same as gross salary?", a: "No. The PF wage is basic plus dearness allowance, while gross also includes other allowances and variable components." },
    { q: "Why do PF figures go wrong?", a: "Usually because the PF wage base is wrong." },
    { q: "Is the ceiling mandatory?", a: "It is described as applying where the employer applies it." },
    { q: "Does LOP change the PF wage?", a: "Yes. Fewer paid days reduce it." },
    { q: "What rate applies to PF wage?", a: "12% from the employee and 12% from the employer." },
    { q: "How does basic pay affect PF wage?", a: "Basic is its main component, which is why the basic/allowance split is a cost decision." },
  ],
  pip: [
    { q: "What is a PIP?", a: "A Performance Improvement Plan: a defined period with milestones, structured support and a decision at the end." },
    { q: "How long is a PIP in HRMagix?", a: "It is structured across 30, 60 and 90 days." },
    { q: "What does a PIP include?", a: "Milestones, structured support, a manager coaching log and an end decision." },
    { q: "Why include interim checkpoints in a PIP?", a: "Without them, a plan with only an end date is a countdown rather than an improvement plan." },
    { q: "What is a coaching log in a PIP?", a: "The manager's record of coaching during the plan." },
    { q: "Does a PIP end in a decision?", a: "Yes, a decision at the end is part of the definition." },
    { q: "Is a PIP the same as probation?", a: "No. Probation assesses initial suitability; a PIP addresses performance within a defined plan." },
    { q: "Where does HRMagix handle PIPs?", a: "Within performance management." },
  ],
  probation: [
    { q: "What is probation?", a: "An initial period during which suitability is assessed." },
    { q: "How does probation end?", a: "In confirmation, extension or separation." },
    { q: "Can probation be extended?", a: "Yes, extension is one of the outcomes." },
    { q: "What is the biggest risk in probation?", a: "No decision: the period lapses and nothing is recorded." },
    { q: "When does an unrecorded probation cause problems?", a: "At an increment or an exit, when the ambiguity shows up." },
    { q: "Should a probation decision be recorded?", a: "Yes. Recording confirmation, extension or separation avoids later ambiguity." },
    { q: "Is probation the same as a PIP?", a: "No. A PIP is a structured improvement plan; probation is an initial suitability period." },
    { q: "Is failing probation always a harsh decision?", a: "The glossary notes the failure mode is not a harsh decision but no decision." },
  ],
  "professional-tax": [
    { q: "What is professional tax?", a: "A tax on employment levied by some Indian states." },
    { q: "Does every state levy professional tax?", a: "No, only some states." },
    { q: "Who sets professional tax slabs?", a: "Each state sets its own slabs, exemptions and periodicity." },
    { q: "Is professional tax the same every month?", a: "Not always. At least one state deducts a different amount in a single month." },
    { q: "How do multi-state employers handle PT?", a: "They run several schedules rather than one." },
    { q: "Is professional tax a central tax?", a: "No, it is levied by states." },
    { q: "Is professional tax the same as TDS?", a: "No. TDS is income tax withheld under Section 192; PT is a state tax on employment." },
    { q: "Are there PT exemptions?", a: "Exemptions exist and are set by each state." },
  ],
  regularisation: [
    { q: "What is attendance regularisation?", a: "A correction to an attendance record raised against a specific day, with a reason, routed for approval." },
    { q: "Does regularisation overwrite the original punch?", a: "No. The original capture is kept alongside the correction." },
    { q: "Why keep the original attendance record?", a: "A ledger that can be overwritten is not evidence of anything." },
    { q: "Does regularisation need approval?", a: "Yes, it is routed for approval." },
    { q: "Is a reason required?", a: "Yes, a reason is attached." },
    { q: "Can employees raise regularisation themselves?", a: "Yes, through self-service; applying is not approving." },
    { q: "Can regularisation fix LOP?", a: "If the day was worked, correcting attendance removes the basis for the unpaid day." },
    { q: "Where is regularisation handled in HRMagix?", a: "In Attendance & Shifts." },
  ],
  "sandwich-rule": [
    { q: "What is the sandwich rule in leave?", a: "Non-working days between two leave days are counted as leave." },
    { q: "Is the sandwich rule mandatory?", a: "No. It is an employer choice, not a statutory requirement." },
    { q: "Does a weekend between leave days count?", a: "Under a sandwich rule policy, yes." },
    { q: "When do companies realise their sandwich policy?", a: "Often only when somebody disputes a deduction." },
    { q: "Who decides if the sandwich rule applies?", a: "The employer's leave policy." },
    { q: "Is the sandwich rule the same in every company?", a: "No. It is an employer choice, so each organisation sets its own position." },
    { q: "Why state the sandwich rule explicitly?", a: "To avoid disputes, since organisations often discover their position only then." },
    { q: "Where can I read more about the sandwich rule?", a: "The blog post on the sandwich rule." },
  ],
  "section-192": [
    { q: "What is Section 192?", a: "The Income Tax Act provision requiring employers to deduct tax at source from salary." },
    { q: "How is TDS under Section 192 calculated?", a: "Projected across the financial year against the regime election and verified declarations." },
    { q: "How is Section 192 TDS reported?", a: "Quarterly on Form 24Q." },
    { q: "How is Section 192 TDS certified?", a: "Annually to the employee on Form 16." },
    { q: "Does the tax regime affect Section 192 TDS?", a: "Yes, TDS is projected against the employee's election." },
    { q: "Why do declarations matter?", a: "Verified declarations feed the TDS projection." },
    { q: "Does Section 192 apply only to salary?", a: "It is the provision for TDS on salary." },
    { q: "Who deducts under Section 192?", a: "The employer." },
  ],
  "self-service": [
    { q: "What is employee self-service?", a: "The employee's own access to their record: payslips, Form 16, leave, attendance regularisation, personal details and declarations." },
    { q: "Can employees download payslips through ESS?", a: "Yes." },
    { q: "Can I get Form 16 via self-service?", a: "Yes." },
    { q: "Can employees apply for leave via ESS?", a: "Yes, and see balances." },
    { q: "Can employees approve their own requests?", a: "No. Applying is not approving." },
    { q: "Can investment declarations be submitted via ESS?", a: "Yes." },
    { q: "Why is ESS scope narrow?", a: "To keep applying separate from approving." },
    { q: "Where is ESS in HRMagix?", a: "The Employee Self-Service solution." },
  ],
  shift: [
    { q: "What is a shift?", a: "A defined working window that attendance is measured against." },
    { q: "How are night shifts across midnight counted?", a: "As one unit attributed to the day it began." },
    { q: "Why not split night shifts at midnight?", a: "Splitting produces two short days and an incorrect overtime figure." },
    { q: "Which day does a night shift belong to?", a: "The day it began." },
    { q: "How does grace period relate to shifts?", a: "It is a window after shift start before arrival counts as late." },
    { q: "Can working on an off day earn comp-off?", a: "Yes, work on a non-working day can earn comp-off." },
    { q: "Where are shifts managed in HRMagix?", a: "Attendance & Shifts." },
    { q: "Where can I learn more about midnight shifts?", a: "The blog post on shift detection across midnight." },
  ],
  "take-home": [
    { q: "What is take-home salary?", a: "Net pay: what reaches the employee's bank account." },
    { q: "How is take-home calculated?", a: "Gross less the employee's statutory contributions, TDS and other authorised deductions." },
    { q: "Is take-home the same as CTC?", a: "No. CTC is the employer's total cost; take-home is lower." },
    { q: "Is take-home the same as gross?", a: "No. Gross is before deductions." },
    { q: "Does the employee's PF reduce take-home?", a: "Yes, as a statutory contribution." },
    { q: "Does TDS reduce take-home?", a: "Yes." },
    { q: "Where is take-home shown?", a: "As net pay on the payslip." },
    { q: "How can I estimate take-home?", a: "The salary calculator." },
  ],
  tds: [
    { q: "What is TDS?", a: "Tax deducted at source: withheld by the payer and deposited with the government on the recipient's behalf." },
    { q: "Which section covers TDS on salary?", a: "Section 192." },
    { q: "How is salary TDS computed?", a: "Projected across the financial year." },
    { q: "How is TDS certified to employees?", a: "Annually on Form 16." },
    { q: "How is salary TDS reported?", a: "Quarterly on Form 24Q." },
    { q: "Does tax regime affect TDS?", a: "Yes, the regime election drives TDS for the year." },
    { q: "Does TDS reduce take-home?", a: "Yes." },
    { q: "Who deposits TDS?", a: "The payer, on the recipient's behalf." },
  ],
  tenure: [
    { q: "What is tenure in HR?", a: "Time from date of joining to today, or to the last working day for leavers." },
    { q: "How should tenure be reported?", a: "As a distribution by grade, function or location." },
    { q: "Why avoid average tenure?", a: "It tends to conceal the pattern worth seeing." },
    { q: "How is tenure measured for ex-employees?", a: "To the last working day." },
    { q: "Is tenure the same as attrition?", a: "No. Tenure is time served; attrition is the rate of leaving." },
    { q: "Can tenure explain attrition?", a: "Reading attrition by tenure band shows where departures concentrate." },
    { q: "When does tenure start?", a: "At the date of joining." },
    { q: "How does tenure relate to continuous service?", a: "Both run from joining; continuous service is what statutory tests like gratuity use." },
  ],
  uan: [
    { q: "What is UAN?", a: "Universal Account Number, the permanent identifier for a provident fund member." },
    { q: "Does UAN change with a new job?", a: "No. It stays with the individual across employers." },
    { q: "What does UAN link?", a: "The member IDs across employers." },
    { q: "When should UAN be verified?", a: "Before the first payroll run." },
    { q: "Why must UAN be correct early?", a: "It is one of the identifiers that must be right before payroll, not after." },
    { q: "Who is UAN issued to?", a: "Provident fund members." },
    { q: "Is UAN part of EPF?", a: "Yes, it identifies EPF members." },
    { q: "Is UAN the same as a PF member ID?", a: "No. UAN is the permanent identifier that stays with the individual and links their member IDs across employers." },
  ],
  "wage-register": [
    { q: "What is a wage register?", a: "The record of wages paid, in the form the applicable legislation prescribes." },
    { q: "Must the wage register be produced on demand?", a: "Yes." },
    { q: "How is a wage register tested?", a: "On a specific person and date rather than its totals." },
    { q: "Who prescribes the format?", a: "The applicable legislation." },
    { q: "Wage register vs muster roll?", a: "The wage register records wages; the muster roll records attendance." },
    { q: "Are totals enough?", a: "No, entries for individuals must stand up." },
    { q: "Where do wage register figures come from?", a: "From the payroll runs that paid the wages." },
    { q: "Why is the wage register compared to the muster roll?", a: "Like the muster roll, it is tested on a specific person and date rather than on its totals." },
  ],
};
