import type { PageFaq } from "./types";

/** FAQs for glossary terms added in the expansion, keyed by term slug. */
export const glossaryMoreFaqsA: Record<string, PageFaq[]> = {
  hris: [
    { q: "What data should an HRIS hold for each employee?", a: "At minimum: personal and contact details, date of joining, designation, department, reporting manager, statutory identifiers such as UAN and PAN, and bank details. Each change, such as a transfer or promotion, should be stored with the date it took effect so past positions can be reconstructed." },
    { q: "Why does effective dating matter in an HRIS?", a: "Payroll, audits and headcount reports often ask what was true on a past date, not what is true today. If the record is simply overwritten, a backdated increment or an inspection query about last year's staff cannot be answered reliably." },
    { q: "Can a spreadsheet work as an HRIS for a small company?", a: "It can hold the data, but it rarely keeps a history of changes, controls who can edit what, or stops two versions drifting apart. Those gaps usually show up first when payroll and HR keep separate sheets that disagree." },
    { q: "Who should own the HRIS data?", a: "HR normally owns the employee record, with payroll and managers reading from it rather than keeping their own copies. A single owner makes it clear who corrects an error and who approves changes to sensitive fields such as bank details." },
  ],
  hcm: [
    { q: "Is HCM software only for large companies?", a: "The label is used most by vendors selling to large organisations, but the scope it describes applies at any size. A smaller company should judge a product on the processes it actually needs rather than on whether it is called HCM." },
    { q: "What does an HCM suite usually include beyond HR records?", a: "Typically recruitment, onboarding, payroll, performance, learning and succession planning, sometimes with workforce analytics. Not every suite covers all of these well, so it is worth checking which modules are native and which are add-ons." },
    { q: "How is HCM different from talent management?", a: "Talent management is one part of HCM, focused on hiring, developing and retaining people. HCM also covers the administrative core, such as records, pay and statutory compliance." },
    { q: "What should I check before buying an HCM product in India?", a: "Check that payroll handles Indian statutory items such as PF, ESI, Professional Tax and TDS, and that state-specific rules are configurable. Global suites sometimes rely on a local partner for Indian payroll, which adds an integration to maintain." },
  ],
  peo: [
    { q: "Is a PEO the same as an employer of record (EOR)?", a: "The terms overlap and are often used loosely. In common usage an EOR takes on full legal employment, frequently for staff in a country where the client has no entity, while PEO describes a co-employment arrangement; the contract defines the actual split." },
    { q: "Who files PF and ESI returns under a PEO arrangement?", a: "The PEO, because the staff are covered under its registrations. The client should still ask for proof of deposit each month, since unpaid contributions can become a dispute about who was the principal employer." },
    { q: "When does a company typically use a PEO?", a: "When it needs to hire in a state or country before setting up its own registrations, or when it wants to hand off statutory administration entirely for a small team. Many companies move staff onto their own payroll once headcount grows." },
    { q: "What are the risks of using a PEO?", a: "The main risks are liability that is unclear in the contract, weak visibility into deposits and filings, and disruption to employees when moving them off the PEO later. Staff may also see a different company name on payslips and Form 16, which needs explaining." },
  ],
  ats: [
    { q: "What does an ATS track?", a: "Open positions, applications, the stage each candidate is at, interview feedback and the final decision. Good systems also record where each candidate came from, so the cost and yield of each sourcing channel can be compared." },
    { q: "Do candidates need to apply directly into an ATS?", a: "No. Applications from job boards, referrals, agencies and email can usually be added, though importing them by hand is where duplicates and lost CVs tend to appear." },
    { q: "How does an ATS connect to onboarding?", a: "When a candidate accepts an offer, their details should pass into the employee record so they are not typed in again. Re-entry at this point is a common source of spelling and date errors in payroll." },
    { q: "Does an ATS need to handle candidate data carefully?", a: "Yes. Candidate CVs contain personal data, so access should be limited, and rejected candidates' data should not be kept longer than the organisation's retention policy allows. Check the current requirements under India's data protection law." },
  ],
  hra: [
    { q: "How is the HRA exemption calculated?", a: "Under the old regime, the exempt amount is the least of the HRA actually received, rent paid minus 10% of salary, and 50% of salary for specified metro cities or 40% elsewhere, where salary means basic plus DA forming part of retirement benefits. The balance of HRA is taxable." },
    { q: "Is the HRA exemption available under the new tax regime?", a: "No. Under the new regime, HRA is fully taxable, so the exemption only matters for employees who choose the old regime. Check the current position each year, as the Finance Act can change it." },
    { q: "Can an employee claim HRA while paying rent to a parent?", a: "It is generally accepted if the rent is genuinely paid, the parent owns the property and the parent reports the rent as income. Payroll should still collect the same proof as for any other landlord." },
    { q: "What if an employee does not submit rent receipts?", a: "Payroll treats the HRA as taxable and deducts TDS accordingly. The employee may still be able to claim the exemption in their own return if they have the evidence." },
  ],
  lta: [
    { q: "What travel costs does LTA cover?", a: "Only the fare for travel within India by the shortest route, for the employee and eligible family members. Hotel, food and local sightseeing costs are not covered." },
    { q: "How many LTA claims can be made?", a: "Two journeys in a block of four calendar years, under section 10(5) and the related rule. One unused journey can be carried into the first year of the next block." },
    { q: "Is LTA exempt under the new tax regime?", a: "No. The LTA exemption is available only under the old regime. Under the new regime the amount paid is taxable like other salary." },
    { q: "What proof should payroll collect for an LTA claim?", a: "Tickets or boarding passes and proof of payment for the journey, with the travel dates and the family members who travelled. The claim should be raised in the financial year the journey was made." },
  ],
  "special-allowance": [
    { q: "Why do salary structures have a special allowance?", a: "It usually absorbs the difference between the agreed CTC and the sum of the named components. That makes it easy to hit a CTC figure, but it can hide how the package was built." },
    { q: "Is special allowance taxable?", a: "Yes, a general special allowance is fully taxable as salary. It is different from specific allowances that have their own exemptions under the old regime." },
    { q: "Does PF apply to special allowance?", a: "PF wages are defined as basic plus DA, but allowances paid universally to all employees can be treated as part of basic for PF purposes under case law. Splitting pay to keep the PF wage artificially low is a known area of inspection, so take advice on your structure." },
    { q: "How does the labour codes' wage definition affect special allowance?", a: "The Code on Wages defines wages so that excluded allowances above a set share of total pay are added back. If and as notified, a large special allowance may increase the wage used for PF and gratuity; check the current status before restructuring." },
  ],
  "variable-pay": [
    { q: "How is variable pay shown in a CTC?", a: "Usually as a target amount, with a note that the actual payout depends on individual, team or company performance. Offer letters should state clearly that it is not guaranteed, to avoid disputes later." },
    { q: "When is variable pay taxed?", a: "In the year it is actually paid, not the year it relates to. TDS is deducted in the month of payout, which often pushes that month's deduction up." },
    { q: "Is variable pay counted for PF?", a: "Generally no, because PF wages are basic plus DA and performance incentives sit outside them. Check whether the structure meets the wage definition under the labour codes if they apply." },
    { q: "What happens to variable pay when an employee resigns?", a: "It depends on the plan document. Many plans require the employee to be on the rolls on the payout date, while others pay pro-rata; the rule should be written down before the year starts." },
  ],
  reimbursements: [
    { q: "How are reimbursements different from allowances?", a: "An allowance is a fixed amount paid regardless of spend, while a reimbursement repays an actual, documented expense up to a limit. Reimbursements need bills; allowances do not." },
    { q: "Are reimbursements taxable?", a: "Expenses incurred wholly for the employer's business, such as client travel, are not income. Personal-benefit items paid as reimbursements may be taxable or treated as perquisites depending on the item and the regime." },
    { q: "What happens to unclaimed reimbursements at year end?", a: "If the structure pays a fixed reimbursement entitlement and bills are not submitted, the unclaimed amount is usually paid out as taxable salary. The policy should state the cut-off for submitting bills." },
    { q: "What records should be kept for reimbursements?", a: "The original or digital bill, the approval, and the payout date. Auditors and tax officers look for the link between each payment and its supporting document." },
  ],
  perquisites: [
    { q: "How are perquisites valued for tax?", a: "Under Rule 3 of the Income-tax Rules, which sets valuation methods for items such as company accommodation, cars, interest-free loans and ESOPs. The valued amount is added to taxable salary." },
    { q: "Where do perquisites appear in year-end documents?", a: "In Form 12BA, which lists each perquisite and its value, and in the salary figures in Form 16. Employees use these when filing their returns." },
    { q: "Is a company-provided laptop a perquisite?", a: "Equipment such as computers provided for work use is generally not taxed as a perquisite. Gifts, club memberships and personal use of assets may be, depending on the rule for each item." },
    { q: "Are perquisites taxed under both regimes?", a: "Yes. The new regime removes many exemptions and deductions, but taxable perquisites remain part of salary income under either regime." },
  ],
  "form-12bb": [
    { q: "When should employees submit Form 12BB?", a: "Usually at the start of the financial year as a declaration, then again with proofs before the employer's cut-off, often around January. The employer uses it to compute TDS for the year." },
    { q: "What does Form 12BB cover?", a: "HRA rent details, LTA claims, interest on a home loan, and deductions under Chapter VI-A such as section 80C. Each claim needs supporting evidence." },
    { q: "When is a landlord's PAN required in Form 12BB?", a: "When annual rent paid exceeds the threshold set in the rules, the landlord's PAN must be given. Payroll should check the current threshold and collect a declaration if the landlord has no PAN." },
    { q: "Is Form 12BB needed under the new tax regime?", a: "Most of the claims it covers are not allowed under the new regime, so employees who opt for it usually have little to declare. They may still need to give details relevant to deductions that the new regime allows." },
  ],
  tan: [
    { q: "Who needs a TAN?", a: "Any employer or other person required to deduct or collect tax at source. A company paying salaries above the taxable limit needs one before it deducts TDS." },
    { q: "Where is the TAN used?", a: "On TDS challans, quarterly TDS returns such as Form 24Q for salaries, and on Form 16 issued to employees. Errors in the TAN can mean deposits are not credited correctly." },
    { q: "Is TAN different from PAN?", a: "Yes. PAN identifies the taxpayer for its own income tax; TAN identifies the deductor for TDS compliance. A company needs both." },
    { q: "Does each branch need its own TAN?", a: "A company can use one TAN, but branches that deduct TDS separately can get separate TANs. Whatever the setup, each payment and return must use the TAN under which the tax was deducted." },
  ],
  "standard-deduction": [
    { q: "Does an employee need to submit proof for standard deduction?", a: "No. It is a flat deduction from salary income allowed without any bills or declarations. Payroll applies it automatically when computing TDS." },
    { q: "Is standard deduction available under both tax regimes?", a: "It is currently allowed under both the old and new regimes, though the amount can differ. The Finance Act sets the amount each year, so check the current figure." },
    { q: "Do pensioners get standard deduction?", a: "Yes, pension received from a former employer is taxed as salary, so the standard deduction applies to it as well." },
    { q: "Can standard deduction be claimed twice when changing jobs?", a: "No. It is one deduction per year regardless of the number of employers. When an employee joins mid-year, payroll should account for it being claimed by the previous employer." },
  ],
  "section-87a-rebate": [
    { q: "How is the section 87A rebate applied in payroll?", a: "Payroll projects the employee's taxable income for the year and, if it falls within the limit, reduces the computed tax by the rebate. The rebate cannot exceed the tax due." },
    { q: "Does the section 87A rebate differ between regimes?", a: "Yes. The income limit and maximum rebate are different under the old and new regimes. The Finance Act sets both each year." },
    { q: "Who is eligible for the 87A rebate?", a: "Resident individuals whose total income is within the limit for the regime they have chosen. Non-residents are not eligible." },
    { q: "Why might an employee owe tax despite the rebate?", a: "If their total income from all sources, not just salary, crosses the limit, the rebate is lost. Some income taxed at special rates may also be treated differently, so check the current rules." },
  ],
  "section-80c": [
    { q: "What investments qualify under section 80C?", a: "Common examples are the employee's PF contribution, VPF, PPF, ELSS mutual funds, life insurance premiums, home loan principal repayment and children's tuition fees. The combined limit is set by the Finance Act." },
    { q: "Does the employee's PF count towards section 80C?", a: "Yes, the employee's own PF and VPF contributions count, so payroll includes them automatically. The employer's contribution does not count under 80C." },
    { q: "Is section 80C available under the new regime?", a: "No. Section 80C deductions are only available to employees who choose the old regime." },
    { q: "What proofs should payroll collect for section 80C?", a: "Premium receipts, investment statements, tuition fee receipts and loan certificates showing principal repaid. Declared amounts without proof by the cut-off are normally removed before the final TDS calculation." },
  ],
  nps: [
    { q: "How is the employer's NPS contribution treated for tax?", a: "The employer's contribution to an employee's NPS account can be deducted under section 80CCD(2), within a percentage of salary set by law. This deduction is also allowed under the new regime." },
    { q: "How is the employee's own NPS contribution treated?", a: "Under the old regime it can be claimed under section 80CCD(1) within the 80C limit, plus an additional deduction under 80CCD(1B). Check the current limits each year." },
    { q: "Can a private employer offer NPS to employees?", a: "Yes, through the corporate NPS model. The employer registers with a Point of Presence and remits contributions on behalf of employees." },
    { q: "Is NPS the same as EPF?", a: "No. EPF is a statutory scheme with a declared interest rate; NPS is a voluntary market-linked pension scheme with different withdrawal rules." },
  ],
  vpf: [
    { q: "How much can an employee contribute to VPF?", a: "Any amount above the mandatory 12% of PF wages, up to 100% of basic plus DA. The employee asks HR in writing, and payroll deducts it alongside the regular contribution." },
    { q: "Does the employer have to match VPF?", a: "No. The employer's statutory contribution stays at 12% of PF wages regardless of what the employee adds voluntarily." },
    { q: "Is interest on VPF tax-free?", a: "Interest on employee contributions above a set annual limit is taxable. Payroll and employees should check the current rule each year." },
    { q: "Can an employee stop VPF midway?", a: "Usually yes, by giving notice to HR, though employers commonly allow changes only at the start of a financial year. The policy should state when changes take effect." },
  ],
  edli: [
    { q: "How much does the employer pay for EDLI?", a: "0.5% of PF wages up to ₹15,000, so the maximum is ₹75 per employee per month. The employee does not contribute to EDLI." },
    { q: "Who receives the EDLI benefit?", a: "The nominee or legal heir of an EPF member who dies while in service. The claim is made to the EPFO with the death certificate and the member's details." },
    { q: "Do all EPF members get EDLI cover?", a: "Yes, all EPF members are covered automatically. Employers can be exempted only if they run an approved group insurance scheme that gives better benefits." },
    { q: "How is the EDLI benefit calculated?", a: "It depends on the member's average wages before death and the PF balance, subject to a minimum and maximum set under the scheme. Check the EPFO notification for current figures." },
  ],
  "epf-admin-charges": [
    { q: "How are EPF admin charges calculated?", a: "0.5% of PF wages, paid by the employer on top of its 12% contribution. Payroll should include it in the employer's PF cost, not deduct it from the employee." },
    { q: "Do EPF admin charges apply on wages above ₹15,000?", a: "They are charged on the PF wages actually used for contributions, so if the employer contributes on wages above ₹15,000 the charge is calculated on that higher amount." },
    { q: "Is there a minimum admin charge?", a: "Yes, a minimum monthly amount applies per establishment. Check the current EPFO notification for the figure." },
    { q: "Should admin charges be shown in CTC?", a: "Many companies include them in CTC as part of the employer's PF cost. Whatever the choice, it should be applied consistently and explained in offer letters." },
  ],
  "leave-encashment": [
    { q: "How is leave encashment calculated?", a: "Usually as unused eligible leave days multiplied by a daily rate, often based on basic plus DA divided by the days the policy specifies. The policy must state the wage base and divisor." },
    { q: "Is leave encashment taxable?", a: "Encashment during service is fully taxable. On retirement or resignation, a portion may be exempt under section 10(10AA) up to a limit set by the government." },
    { q: "Which types of leave can be encashed?", a: "Usually only earned or privilege leave. Casual and sick leave typically lapse, though the company policy and any state rules decide." },
    { q: "Is leave encashment paid in full and final settlement?", a: "Yes, unused encashable leave is normally paid in the final settlement. State Shops and Establishments rules may require it, and these vary by state." },
  ],
  "leave-accrual": [
    { q: "What is the difference between accrual and front-loading leave?", a: "Accrual credits leave gradually, such as monthly, as the employee works. Front-loading credits the full annual entitlement at the start of the year." },
    { q: "Does leave accrue during unpaid leave?", a: "Many policies stop accrual during loss-of-pay periods. The rule should be in the leave policy and applied consistently." },
    { q: "How is accrual handled for a mid-month joiner?", a: "The first month's accrual is usually pro-rated by days worked. Rounding rules should be set so balances do not drift over time." },
    { q: "Can an employee take leave before it accrues?", a: "Some employers allow negative balances for a limited period. If the employee leaves before earning it back, the amount is usually recovered in the final settlement." },
  ],
  "leave-carry-forward": [
    { q: "Is there a limit on carrying forward leave?", a: "Usually yes. The employer's policy sets a cap, and state Shops and Establishments rules may set their own limits, which vary by state." },
    { q: "What happens to leave above the carry-forward limit?", a: "It may lapse or be encashed, depending on the policy. Employees should be told before the year ends so they can plan." },
    { q: "Do casual and sick leave carry forward?", a: "Often not. Casual leave usually lapses at year end, while sick leave may carry forward up to a cap in some policies." },
    { q: "When should carry-forward be processed?", a: "At the end of the leave year, before new entitlements are credited. Running it late often causes temporary negative or duplicate balances." },
  ],
  "earned-leave": [
    { q: "How is earned leave calculated under the Factories Act?", a: "For factory workers, section 79 provides one day of leave for every 20 days worked in the previous calendar year, for workers who have worked 240 days or more. Other establishments follow their state's Shops and Establishments rules, which vary." },
    { q: "Is earned leave the same as privilege leave?", a: "Yes, the terms are used interchangeably, along with annual leave. All describe paid leave earned by service." },
    { q: "Can earned leave be encashed?", a: "Usually yes, either during service under the company policy or at exit as part of the final settlement." },
    { q: "Do holidays count as earned leave days?", a: "Most policies exclude weekly offs and public holidays from leave counts if they fall within the leave period, though some sandwich rules count them. The policy should state which applies." },
  ],
  "casual-leave": [
    { q: "How many casual leave days do employees get?", a: "It depends on the state's Shops and Establishments rules and the company policy, which vary. Many companies give a small fixed number each year." },
    { q: "Does casual leave carry forward?", a: "Usually not. Most policies lapse unused casual leave at the end of the year and do not encash it, because it is meant for short, unplanned needs." },
    { q: "Can casual leave be combined with other leave?", a: "Many policies restrict combining casual leave with earned leave to prevent long absences. The rule should be written in the leave policy." },
    { q: "Is casual leave paid?", a: "Yes, it is paid leave. It does not reduce salary when taken within the available balance." },
  ],
  "sick-leave": [
    { q: "Is a medical certificate needed for sick leave?", a: "Many policies require one only for absences beyond a few consecutive days. The threshold should be stated in the policy." },
    { q: "How does sick leave interact with ESI?", a: "Employees covered by ESI can claim sickness benefit from ESIC for certified sickness, subject to conditions. Employers should check how this interacts with company paid sick leave." },
    { q: "Does sick leave carry forward?", a: "It depends on the policy and state rules. Some allow it to accumulate up to a cap, others lapse it yearly." },
    { q: "Can sick leave be encashed?", a: "Usually not. It is meant for illness rather than as a saving, though some policies differ." },
  ],
  "restricted-holiday": [
    { q: "How many restricted holidays can an employee take?", a: "Typically a small number from a published list, set by company policy. The list is often based on regional and religious festivals." },
    { q: "Is a restricted holiday the same as optional leave?", a: "Yes, the terms are used interchangeably. The employee picks which days to take from the list." },
    { q: "Does an unused restricted holiday carry forward?", a: "Usually not. Unused restricted holidays lapse at year end and are rarely encashed." },
    { q: "Do employees need approval to take a restricted holiday?", a: "Usually yes, applied for like leave so managers can plan cover. Unlike a fixed holiday, the office stays open on that day." },
  ],
  "weekly-off": [
    { q: "Is a weekly off mandatory?", a: "Yes. Factories Act section 52 and state Shops and Establishments rules require a weekly rest day. The specific rules vary by state for shops and establishments." },
    { q: "Can the weekly off be on a day other than Sunday?", a: "Yes, it can be any day fixed by the employer, as long as it is notified and the legal requirements are met." },
    { q: "What if an employee works on a weekly off?", a: "They are usually given a compensatory off or overtime pay, depending on the law and policy." },
    { q: "Does a weekly off count as paid?", a: "For monthly-salaried staff it is paid. For daily-rated workers, state rules and the policy decide." },
  ],
  "half-day": [
    { q: "How is a half-day recorded in attendance?", a: "As half present and half absent or on leave. The policy must define the minimum hours for each half." },
    { q: "Can an employee take half a day of leave?", a: "Many policies allow half-day leave for earned and casual leave. Sick leave rules vary." },
    { q: "How does a half-day affect pay?", a: "If not covered by leave, half a day's pay is usually deducted. The daily rate must be calculated consistently." },
    { q: "Do late arrivals count as half-days?", a: "Some policies convert repeated late marks into half-days. The rule must be clear and communicated." },
  ],
  "shift-allowance": [
    { q: "When is a shift allowance paid?", a: "For working night or rotating shifts outside normal hours, as the company policy sets. Rates vary by employer." },
    { q: "Is shift allowance taxable?", a: "Yes, it is generally taxable as part of salary. It should be shown as a separate earning on the payslip so it can be traced to shifts worked." },
    { q: "Is shift allowance part of PF wages?", a: "Usually not, if it is genuinely paid only for shift work and not universally. Check the structure against the wage definitions." },
    { q: "How is shift allowance calculated?", a: "Often a fixed amount per shift worked, pulled from the roster and attendance. Payroll should match it to actual shifts." },
  ],
  "geo-fencing": [
    { q: "How does geo-fencing attendance work?", a: "The app records the employee's location at check-in and compares it to a defined boundary around the workplace. Check-ins outside are flagged or blocked." },
    { q: "Is employee consent needed for geo-fencing?", a: "Location is personal data, so employees should be told how it is collected and used. Check current data protection requirements in India." },
    { q: "Does geo-fencing work for field staff?", a: "It can, with multiple permitted locations or by recording location at each check-in rather than restricting it." },
    { q: "What are common geo-fencing problems?", a: "Inaccurate GPS indoors, boundaries drawn too tightly, and spoofing apps. Policies should allow a manual correction route." },
  ],
  "biometric-attendance": [
    { q: "Is biometric data sensitive?", a: "Yes. Fingerprints and face data are personal data that need careful handling, storage and consent. Check current Indian data protection requirements." },
    { q: "What if a biometric device fails?", a: "There should be a manual entry or regularisation process with manager approval, so attendance is not lost. Each manual entry should be logged so repeated overrides can be reviewed." },
    { q: "Can biometric attendance be linked to payroll?", a: "Yes, punches from devices can feed payroll for loss-of-pay and overtime. The sync should be checked before the payroll cut-off, since a missed upload looks like an absence." },
    { q: "Are face recognition and fingerprint different in practice?", a: "Face recognition avoids touch and works with masks less reliably; fingerprint can fail with worn or wet fingers. Choice depends on the workplace." },
  ],
  timesheet: [
    { q: "What is the difference between a timesheet and attendance?", a: "Attendance records whether and when someone was present; a timesheet records how that time was spent across tasks, projects or clients. Hours on a timesheet should not exceed the hours attendance shows." },
    { q: "Who approves timesheets?", a: "Usually the project or line manager, on a weekly or monthly cycle. Where one person works across projects, each project owner may approve only their own hours." },
    { q: "Are timesheets used for billing?", a: "Yes, in services firms approved timesheets often support client invoices and project costing. Clients may ask to see them, so entries should describe the work, not just the hours." },
    { q: "What are common timesheet problems?", a: "Late submission, filling in from memory, and mismatch with attendance. Regular reminders and checks help." },
  ],
  roster: [
    { q: "How far ahead should a roster be published?", a: "Far enough for staff to plan, often a week or more. Some state rules require notice of shift changes, which vary." },
    { q: "How does a roster affect payroll?", a: "Shift allowance, overtime and weekly offs depend on the roster, so it should match actual attendance." },
    { q: "Can employees swap shifts?", a: "Many policies allow swaps with manager approval. The swap must be recorded in the roster, otherwise attendance and shift allowance will not match." },
    { q: "What laws limit rostering?", a: "Working hours, rest intervals, weekly off and night work for women are regulated under the Factories Act and state rules, which vary." },
  ],
  headcount: [
    { q: "How is headcount counted?", a: "Usually the number of employees on the rolls on a given date, regardless of hours worked. Reports should state whether people on notice, long leave or probation are included." },
    { q: "Do contractors count in headcount?", a: "They are usually reported separately from employees. Some statutory thresholds count contract labour or all persons employed differently, so check the definition in the specific law." },
    { q: "Why does headcount matter for compliance?", a: "Several laws, such as those covering PF and ESI, apply once an establishment crosses a set number of employees. Monitoring headcount by establishment shows when a new registration becomes due." },
    { q: "How is headcount different from FTE?", a: "Headcount counts people; FTE converts the hours they work into full-time equivalents. Two half-time staff are a headcount of two but one FTE." },
  ],
  fte: [
    { q: "How is FTE calculated?", a: "Divide the total hours worked or contracted by all staff by the standard full-time hours for the same period. If full time is 48 hours a week, someone contracted for 24 hours is 0.5 FTE." },
    { q: "Why use FTE instead of headcount?", a: "It gives a truer picture of capacity and cost when many staff work part-time or reduced hours. Headcount alone would overstate the available working time." },
    { q: "Is FTE used in budgeting?", a: "Yes, workforce budgets are often set in FTEs, with cost per FTE used to compare teams. The budget should state whether FTE is based on contracted or actual hours." },
    { q: "Can FTE exceed headcount?", a: "It can when FTE is based on actual hours and staff work overtime. If it is based on contracted hours, FTE cannot exceed headcount." },
  ],
  "utilisation-rate": [
    { q: "How is utilisation rate calculated?", a: "Billable or productive hours divided by total available hours, expressed as a percentage. Available hours should exclude leave and holidays, or the rate will look lower than it is." },
    { q: "What is a good utilisation rate?", a: "There is no single benchmark; it depends on the role, since managers and support staff carry non-billable work. A rate that stays very high for long periods can signal overload rather than efficiency." },
    { q: "How is utilisation different from productivity?", a: "Utilisation measures how much available time went on productive or billable work; productivity measures what that time produced. A team can be fully utilised and still have low output." },
    { q: "Where does utilisation data come from?", a: "Mostly from approved timesheets, with available hours taken from attendance and the leave calendar. Unapproved or late timesheets make the rate unreliable for the period." },
  ],
};
