import type { PageFaq } from "./types";

/** Page FAQs for HRMagix's own legal pages (app/policy/[slug]), keyed by slug. Strictly from lib/policies.ts. */
export const legalFaqs: Record<string, PageFaq[]> = {
  "privacy-policy": [
    {
      q: "Is HRMagix the data controller or the data processor?",
      a: "Both, in different contexts. HRMagix is the controller of information website visitors submit in enquiries, and the processor of employee records a subscribing company loads into the platform, acting on that company's instruction.",
    },
    {
      q: "Does HRMagix use customer employee data for its own purposes?",
      a: "No. HRMagix processes a customer's employee data on their instruction and for their purposes, and does not use it for its own ends.",
    },
    {
      q: "What information is collected when I submit an enquiry or demo request?",
      a: "What you type into the form, typically a name, work email, phone number, company name and details of your requirement, plus the content of any correspondence and the basic technical information your browser sends with a web request.",
    },
    {
      q: "What employee data does the platform hold on behalf of customers?",
      a: "Identity and statutory identifiers such as PAN, Aadhaar, UAN and ESIC IP number, bank details, employment history, compensation structure, leave balances, attendance records (including location and selfie validation where the customer enables it) and supporting documents.",
    },
    {
      q: "Where is HRMagix platform data hosted?",
      a: "In Indian cloud data centres, encrypted at rest and in transit. Certifications held by the underlying hosting providers belong to those providers, not to HRMagix.",
    },
    {
      q: "How long are employee records retained?",
      a: "For as long as the subscribing company requires them, which for statutory reasons extends beyond the end of an individual's employment. Retention is the customer's decision, exercised through the platform.",
    },
    {
      q: "I am an employee of a company using HRMagix. How do I access or correct my data?",
      a: "Send the request to your employer, because they control that data and HRMagix acts on their instruction. Your own self-service login already shows you most of your record.",
    },
    {
      q: "Can I have my enquiry correspondence deleted?",
      a: "Yes. If you are a website visitor, write to HRMagix directly and the enquiry correspondence will be removed.",
    },
  ],
  "terms-of-service": [
    {
      q: "What does an HRMagix subscription include?",
      a: "Access to the platform on the web at app.hrmagix.com and through the HRMagix mobile applications, covering the modules included in the plan you selected.",
    },
    {
      q: "How is HRMagix billed?",
      a: "Plans are published per employee per month, and after the trial, subscriptions are billed per employee per month against the selected plan.",
    },
    {
      q: "Who owns the data loaded into HRMagix?",
      a: "The subscribing company. Employee records, attendance history, payroll runs and documents loaded into or generated by the platform belong to you, while HRMagix owns the software, its interfaces and supplied templates.",
    },
    {
      q: "Is HRMagix responsible for statutory filings and payments?",
      a: "No. HRMagix calculates statutory deductions and produces filing-ready output such as the ECR file, ESIC return, Professional Tax working, Form 24Q and Form 16 Part B, but the legal obligation to file, pay and be correct remains the employer's.",
    },
    {
      q: "Does HRMagix become our employer of record?",
      a: "No. HRMagix helps you configure structures, locations and declarations correctly, but does not become your employer of record by doing so.",
    },
    {
      q: "What counts as acceptable use of the platform?",
      a: "Using it to manage your own workforce. You may not probe or breach its security, store data unrelated to employment administration, or resell access without a written arrangement.",
    },
    {
      q: "Is there a free trial, and what happens if we cancel?",
      a: "A fourteen-day trial gives full access with no setup fee. You may cancel at any time, and should arrange your data export before access ends.",
    },
    {
      q: "What support comes with a subscription?",
      a: "Product specialists in Pune provide support over WhatsApp, phone and email, and Enterprise subscriptions include a dedicated customer success manager.",
    },
  ],
  security: [
    {
      q: "Where is HRMagix payroll and employee data stored?",
      a: "In Indian cloud data centres, a deliberate choice for a product built around Indian statutory compliance.",
    },
    {
      q: "Is data encrypted in HRMagix?",
      a: "Yes. Data is encrypted in transit between your browser or mobile app and the platform, and at rest in storage, including documents in the employee vault.",
    },
    {
      q: "How does HRMagix control who can see salary data?",
      a: "Access is role-based. Employees see their own record, managers see what their role permits for their team, and HR and payroll roles are scoped separately because a leave balance and a salary structure are different privileges.",
    },
    {
      q: "Does HRMagix support multi-factor authentication and single sign-on?",
      a: "Multi-factor authentication is available, and single sign-on is available on the Enterprise plan.",
    },
    {
      q: "Can permissions be separated across legal entities?",
      a: "Yes. Per-entity permissions are supported in multi-entity structures.",
    },
    {
      q: "Does HRMagix keep an audit trail?",
      a: "Approvals, document actions and payroll runs leave a dated trail, and employee records are versioned rather than overwritten, so past states can be reviewed as they were.",
    },
    {
      q: "How often is data backed up?",
      a: "Automated backups run daily, with retention and restoration treated as one subject.",
    },
    {
      q: "Is HRMagix ISO or SOC certified?",
      a: "HRMagix does not claim its own ISO, SOC or comparable certification and does not publish a penetration-test report or bug-bounty programme. For procurement assurance needs, ask the team directly.",
    },
  ],
  "cookie-policy": [
    {
      q: "Does hrmagix.com use cookies?",
      a: "No. The marketing website sets no cookies at all; the three things it stores are held in your browser's local storage, session storage and IndexedDB.",
    },
    {
      q: "What does the website store in my browser?",
      a: "Three items: hrmagix-theme in local storage, hrmagix:sticky-cta-dismissed in session storage, and an IndexedDB database called hrmagix-policies.",
    },
    {
      q: "What is the hrmagix-theme value for?",
      a: "It is set only if you choose light or dark with the theme control, and holds just that word. Without it, the site follows your device's appearance setting.",
    },
    {
      q: "Are custom policy PDFs I add uploaded to HRMagix?",
      a: "No. PDFs added with the Add Custom Policy control are stored in your own browser's IndexedDB so you can view and download them, and are not uploaded anywhere.",
    },
    {
      q: "Does the site use analytics or tracking pixels?",
      a: "No. There are no advertising cookies, cross-site tracking, third-party analytics or tag-manager scripts, social media pixels or fingerprinting.",
    },
    {
      q: "How can I verify what the site stores?",
      a: "Open your browser's developer tools, check the network requests and storage for the page, and compare them against the three entries named in the policy.",
    },
    {
      q: "How do I remove what the site has stored?",
      a: "Clear site data for the domain. The site keeps working, and any custom policy PDFs you added are deleted too, since your browser was the only place they were held.",
    },
    {
      q: "Does the HRMagix app use cookies?",
      a: "app.hrmagix.com uses a session cookie to keep you signed in, a functional requirement rather than tracking. What the product stores is covered by the privacy policy.",
    },
  ],
};
