import type { PageFaq } from "./types";

/** Page-specific FAQs for resource hubs, keyed by route path. */
export const resourcesFaqs: Record<string, PageFaq[]> = {
  "/resources": [
    { q: "Do I need to give an email address to read HRMagix resources?", a: "No. There are no email gates, download forms or lead-capture walls in front of any paper, guide or calculator in the resource centre." },
    { q: "What kinds of material are in the resource centre?", a: "Four kinds: calculators for when you need a number, Insights for when a statutory head is behaving oddly, white papers for when you are making a decision, and the policy library for when you need the document itself." },
    { q: "Are the white papers based on survey data or benchmarks?", a: "No. They are position papers rather than research, containing no survey data, benchmarks or customer outcomes, because none have been gathered. What they offer is reasoning you can disagree with." },
    { q: "Why are the briefings web pages instead of PDFs?", a: "It is a deliberate choice: a PDF behind a form is a lead-generation tool, so each briefing is published as a readable web page instead." },
    { q: "Are the Insights articles only useful if I use HRMagix?", a: "No. Each piece is about a payroll or HR mechanism rather than a product, and is written to be useful whether or not you ever use HRMagix." },
    { q: "Does the policy library state notice periods or leave quotas?", a: "No. The explanatory policy pages state no rules, because a figure written there would be an invented rule attributed to an employer's document. They set out the questions instead." },
    { q: "Is anything I type into the calculators sent to HRMagix?", a: "No. The calculators run entirely in your browser on the figures you enter; nothing is submitted." },
    { q: "What if I cannot find the answer I need here?", a: "For a question about how a particular statutory head is implemented, the fastest route is to ask the team directly through the contact page." },
  ],
  "/resources/calculator": [
    { q: "Which payroll calculators does HRMagix offer?", a: "Each calculator has its own page, covering salary breakup and take-home, PF, ESI, gratuity, total payroll cost and HRMagix plan cost, among others listed on this page." },
    { q: "Can I check the calculator results by hand?", a: "Yes. Every result shows the full breakdown, the rate or rule behind each line, the formula in full and what the calculation does not include, so each number can be reproduced by hand." },
    { q: "Why is there no TDS calculator?", a: "Income tax under Section 192 depends on the old or new regime election, slab rates set by the Finance Act each year and verified declarations, so a standalone calculator would produce a confident but unreliable number." },
    { q: "Why is there no professional tax calculator?", a: "Professional Tax is a state subject whose slabs, exemptions and periodicity differ by state, and Maharashtra deducts a different amount in one month of the year." },
    { q: "Why is there no Labour Welfare Fund calculator?", a: "LWF runs on state calendars, half-yearly in some states and annual in others, on dates unrelated to the payroll cycle." },
    { q: "Where are TDS, PT and LWF calculated then?", a: "Inside the HRMagix payroll run, where the registrations and declarations that make them answerable actually exist." },
    { q: "What figures does the plan cost calculator use?", a: "It uses the published HRMagix plan rates shown on the pricing page." },
    { q: "Do the calculators apply state-specific rules?", a: "The statutory calculators apply provisions of central Indian statute; state-set heads are not offered as standalone calculators." },
  ],
  "/resources/payroll-resources": [
    { q: "How is the payroll resources page organised?", a: "By what you are trying to do rather than by format: work out a figure, diagnose a wrong number, set payroll up, find the statutory rule, or explain payroll to someone else." },
    { q: "How is this different from the main resources page?", a: "The main resources page groups material by format. This page indexes the same payroll material by task, because someone mid-problem does not know which format holds the answer." },
    { q: "Where do I start if I am moving payroll to a new system?", a: "Start with the guide on running your first payroll in a new system, which covers switch timing, the employee master, carrying year-to-date figures and running a parallel month." },
    { q: "Why does my ESI eligibility not change when pay crosses the threshold mid-year?", a: "Eligibility is fixed for the contribution period rather than retested every month. The linked Insights piece on the ESI threshold works through why." },
    { q: "Why do attendance reports and payroll runs sometimes disagree?", a: "The most common reason is shifts that cross midnight. The linked article on shift detection across midnight explains the mechanism." },
    { q: "Where can I find the statutory rules for EPF, ESI, PT, LWF and TDS?", a: "The compliance page covers what applies when, the basis each is computed on and the file the run produces, and the glossary defines the underlying terms." },
    { q: "Is there a professional tax or LWF calculator here?", a: "No. Both are state subjects whose slabs and periodicity vary, so they are computed inside the payroll run rather than offered as standalone calculators." },
    { q: "What should I share with a finance lead who wants the reasoning?", a: "The white papers on the chain of custody from punch to payslip, the exceptions engine and multi-state compliance are written for exactly that conversation." },
  ],
  "/resources/hrms-comparison": [
    { q: "Does this comparison rate specific HRMS vendors?", a: "No. It compares three approaches, spreadsheets, point tools and an integrated HRMS, and names no product other than HRMagix, because other vendors' software has not been evaluated." },
    { q: "When are spreadsheets still the right choice for HR?", a: "Under about ten people, with no statutory registrations yet and everyone visible to everyone, a spreadsheet is the proportionate answer. Move when obligations with fixed dates arrive." },
    { q: "What is the main weakness of using separate point tools?", a: "The employee exists once per tool, so keeping copies in step becomes a monthly export task, and the export is where errors enter. Adding an employee means creating them in each tool separately." },
    { q: "Why does the attendance-to-payroll handover matter so much?", a: "Paid days decide the salary, the PF wage and sometimes the ESI contribution, and the handover happens under the most time pressure, making it the most common source of payroll error." },
    { q: "Why do effective-dated records matter?", a: "Inspections, disputes and diligence ask what the position was on a specific date. Only a system that records when a change took effect can answer that; a spreadsheet edited in place cannot." },
    { q: "What happens to continuity of service when a company adds a second entity?", a: "In an integrated HRMS the entity is a field on the record, so transfers preserve continuity. Recreating someone in a second system can make them appear to start again, affecting gratuity and leave accrual." },
    { q: "How can I tell which approach my company is actually running?", a: "Count how many places a new joiner's details must be entered, ask who reconciles attendance to payroll and when, and ask for a past date's position rather than a past file." },
    { q: "Why do new HR systems fail in the first 90 days?", a: "Usually because setup was never completed, one person configured it alone, only one administrator knew it, or employees never adopted self-service." },
  ],
  "/resources/media-room": [
    { q: "What can journalists attribute to HRMagix?", a: "That it is a single platform of twelve integrated modules on one employee record, that statutory deductions are calculated within the payroll run, its biometric integrations, its published pricing, and that it operates from Maharashtra." },
    { q: "What claims should not be attributed to HRMagix?", a: "Market share, category leadership or competitive comparisons, certification claims about HRMagix itself, customer names or outcomes beyond published testimonials, and headcount, funding, revenue or growth figures." },
    { q: "Does HRMagix have a press-release archive?", a: "No. HRMagix has no press-release archive or published coverage, so this page is an attribution guide instead." },
    { q: "Which biometric devices does HRMagix integrate with?", a: "eSSL, Matrix, Realtime and ZKTeco biometric hardware, over a secure API push or a local sync service." },
    { q: "How should the company name be written?", a: "HRMagix, as one word with capital H, R and M. Not HR Magix, HRmagix or Hrmagix." },
    { q: "How do I request an interview or a quotation?", a: "Write to the contact email on this page ahead of your deadline so the right person can respond. Product and compliance questions are best directed to the team in Pune." },
    { q: "Where can I get the HRMagix logo and boilerplate?", a: "The press kit carries the wordmark spelling, the vector mark, the brand palette with hex values, short and long boilerplate, and usage rules." },
    { q: "What are the commercial facts I can report?", a: "Three published plans priced per employee per month, a fourteen-day free trial with full access to every module and no credit card, and no setup or implementation fee." },
  ],
  "/resources/hr-guides": [
    { q: "Who are the HRMagix HR guides written for?", a: "For people who have been handed a task rather than a topic, such as someone running a first payroll in a new system or setting up attendance for a shift workforce." },
    { q: "How are the guides structured?", a: "Each is chaptered in the order the work actually runs and ends in a checklist rather than a conclusion." },
    { q: "Is there a guide on switching payroll systems?", a: "Yes. Running your first payroll in a new system covers when to switch, getting the employee master right, loading registrations, carrying year-to-date figures and running a parallel month." },
    { q: "Is there a guide on writing a leave policy?", a: "Yes, Writing a leave policy that survives contact with a year is one of the guides listed on this page." },
    { q: "How do guides differ from Insights articles?", a: "Insights are short and diagnostic, about one mechanism that goes wrong. Guides are longer and instructional, for when the work is already yours." },
    { q: "How do guides differ from the white papers?", a: "White papers are positions about how HR and payroll systems should be structured; read one when choosing an approach. Guides tell you how to do the work in order." },
    { q: "How long does each guide take to read?", a: "Each entry lists its number of chapters and approximate reading time in minutes, so you can judge whether it is worth your afternoon." },
    { q: "Where can I look up terms the guides use?", a: "The HR and payroll glossary defines the terms these guides use, and the calculators let you run the statutory formulas on your own numbers." },
  ],
  "/resources/white-papers": [
    { q: "What topics do the HRMagix white papers cover?", a: "Five briefings: payroll as a chain of custody, multi-state compliance, the manufacturing exceptions engine, the startup policy vacuum, and the arithmetic of employee self-service." },
    { q: "Are the white papers free to read without signing up?", a: "Yes. None of them is behind a form or email gate, and each paper is complete on its own page." },
    { q: "Can I download the white papers as PDFs?", a: "No. They are readable web documents rather than downloadable PDFs, which is why no download control appears on the page." },
    { q: "Who are the white papers written for?", a: "For the person doing the job rather than the person approving the purchase; each paper names its intended reader." },
    { q: "Do the papers distinguish law from product claims?", a: "Yes. Each states plainly which parts are provisions of Indian law, which are HRMagix capabilities, and which are opinion." },
    { q: "Is anything held back from the web versions?", a: "No. Nothing has been held back for a version you have to ask for." },
    { q: "Can I see what a paper covers before opening it?", a: "Yes. Each listing shows the paper's subtitle, reader, reading time, abstract and its own table of contents." },
    { q: "Where can I find shorter reading on the same subjects?", a: "Insights carries shorter pieces on the same subjects, written as arguments rather than references." },
  ],
  "/resources/hr-and-payroll-glossary": [
    { q: "What does the HR and payroll glossary cover?", a: "Indian statutory provisions, ordinary payroll vocabulary, and the words this site uses for parts of the platform, such as EPF, ESI, CTC, LOP, PF wage, comp-off, 9-box and Form 16." },
    { q: "Does the glossary explain the difference between CTC and salary?", a: "Yes. Where two terms are habitually confused, such as CTC and salary, an OKR and a KRA, or a regularisation and an edit, the entry says which is which." },
    { q: "Why do some glossary entries include rates and others do not?", a: "A rate appears only where central statute fixes it, such as PF contributions, ESI rates and threshold, and the gratuity formula. State-set items like professional tax are described as varying." },
    { q: "Why does the glossary not give professional tax slabs?", a: "Professional tax and the labour welfare fund are set by states, so a single slab printed here would be wrong for most employers reading it." },
    { q: "Is the glossary tax or legal advice?", a: "No. It is a vocabulary, written so that a conversation with someone who does give that advice is a shorter one." },
    { q: "How do I find a term quickly?", a: "Use the search field or the A to Z rail; because the glossary is one long list, your browser's find-in-page also works." },
    { q: "Where can I apply the formulas defined in the glossary?", a: "The calculators run the statutory formulas defined here on your own figures." },
    { q: "Where can I see how these terms work inside a payroll run?", a: "The compliance page explains how each statutory head is derived inside the payroll run." },
  ],
  "/insights": [
    { q: "What does HRMagix Insights write about?", a: "Indian payroll and people operations, such as ESI against a moving wage base, multi-state Professional Tax, comp-off, the sandwich rule and reading a payslip line by line." },
    { q: "Who are the Insights articles written for?", a: "For the person doing the job: the payroll lead closing a cutoff, the plant head with three shift patterns, the founder who has not written a leave policy yet." },
    { q: "What subjects can I browse Insights by?", a: "Payroll and statutory, attendance and time, leave and policy, and people operations." },
    { q: "Where do the articles get their information?", a: "From one of three sources: a provision of Indian law, a published HRMagix product capability, or the structural logic of the problem, each labelled where it appears." },
    { q: "Do the articles include survey data or benchmarks?", a: "No. HRMagix has no research programme and has published no survey data, industry benchmarks or customer anecdotes, so none appear here." },
    { q: "Why is the archive a list rather than image cards?", a: "When the subjects are this close together, titles and intended readers tell you more than thumbnails do." },
    { q: "How are Insights different from the white papers?", a: "Insights are shorter pieces on a specific mechanism; the white papers are longer arguments about how HR and payroll systems should be structured." },
    { q: "Can I check the figures discussed in an article?", a: "Yes. The calculators let you run the statutory formulas on your own numbers, with the working shown." },
  ],
  "/hr/topics": [
    { q: "What are the HR topics guides?", a: "Practical guides to the work of HR and payroll in India, each covering what the practice is, why it matters, how to run it and the mistakes to avoid." },
    { q: "Which areas do the HR topics cover?", a: "Five areas: time and attendance, pay and compliance, performance and growth, the employee lifecycle, and people and culture." },
    { q: "Do the topic guides include statistics or case studies?", a: "No. They contain no statistics and no case studies, just the practice." },
    { q: "Are the topics specific to India?", a: "Yes. They are written for HR and payroll in India, including statutory deductions and running a payroll month." },
    { q: "Is there a guide on onboarding and exits?", a: "Yes. The employee lifecycle area runs from the offer letter to the final settlement." },
    { q: "How do HR topics differ from the HR guides?", a: "Topics explain a practice plainly. The HR guides are longer, chaptered and end in a checklist for someone doing a specific task." },
    { q: "Where can I find definitions of the terms used?", a: "The HR and payroll glossary defines Indian HR and payroll terms." },
    { q: "Where does each practice live in HRMagix?", a: "The features page shows where each practice is handled in the platform." },
  ],
  "/policy-centre": [
    { q: "What policies are in the HRMagix policy centre?", a: "Two kinds: HRMagix's own commitments (privacy, terms of service, security and cookie policies) and the workplace policy library of templates you issue to your own employees." },
    { q: "Are the workplace policy templates HRMagix's own HR policies?", a: "No. They are your policies, not ours; you write your own rules into them and issue them to your employees." },
    { q: "How many workplace policy templates does HRMagix ship?", a: "Twenty-five: a code of conduct and twenty-four policies covering conduct, attendance, leave, performance, pay and separation." },
    { q: "Where do the policy templates live in the product?", a: "Inside the Documents module." },
    { q: "How is policy acknowledgement tracked?", a: "The platform records acknowledgement per employee per policy version, so a revised policy is not covered by an earlier acceptance." },
    { q: "Is HRMagix a data controller or a processor?", a: "HRMagix is a controller of the information you give it directly and a processor of the employee records you load into the platform." },
    { q: "Why keep company policies and workplace templates separate?", a: "Keeping the roles distinct avoids appearing to claim customers' HR policies as HRMagix's own and keeps the privacy policy comprehensible." },
    { q: "Where can I read what the website stores in my browser?", a: "The cookie policy, listed among HRMagix's commitments on this page." },
  ],
  "/policy-centre/workplace-policy-library": [
    { q: "What HR policy templates are included in the library?", a: "A code of conduct and twenty-four workplace policies covering conduct, attendance, leave, performance, pay and separation, each with its own page." },
    { q: "Do the templates state notice periods or probation lengths?", a: "No. Operative rules such as notice periods, late-arrival grace windows, increment cycles and probation lengths belong to each employer, so you write them into your own copy." },
    { q: "Do I need to adopt all twenty-five policies at once?", a: "No. A fifty-person company does not need all twenty-five on day one; conduct, attendance, leave and separation are the usual starting set." },
    { q: "How is acknowledgement recorded?", a: "Policies are issued to the employees each applies to, and acknowledgement is recorded per employee, per policy version." },
    { q: "What happens when I revise a policy?", a: "A new version re-opens acknowledgement rather than letting an earlier acceptance stand for the new wording." },
    { q: "Can I download the policy documents?", a: "Where a policy document has been supplied, it can be viewed or downloaded as a PDF from the library." },
    { q: "Are these templates legal advice?", a: "No. They are a starting structure; have your own advisers review the final text against the states you operate in before issuing it." },
    { q: "Where are these policies usually issued first?", a: "Most policies are first issued during onboarding, and acknowledgement is recorded and versioned in employee management." },
  ],
};
