import type { PageFaq } from "./types";

/**
 * Page FAQs for /policy/workplace-policies/[slug], keyed by slug.
 * Every answer is grounded in lib/policyDetail.ts and lib/policies.ts: what the
 * policy is for, who it applies to, what the employer defines and what HRMagix
 * records. No rule, duration or quota is stated that the source does not state.
 */
export const workplacePolicyFaqs: Record<string, PageFaq[]> = {
  "code-of-conduct": [
    { q: "What does a code of conduct policy cover?", a: "It states the standard of professional behaviour expected of everyone, the integrity expected in dealing with colleagues, customers and money, and the care expected in using company property and information." },
    { q: "Who does the code of conduct apply to?", a: "Every employee, at every grade and location, from the date of joining." },
    { q: "How does the code of conduct relate to other workplace policies?", a: "Every other policy in the register is subordinate to it. A specific policy on harassment or absconding is easier to apply consistently when there is a general standard it refers back to." },
    { q: "What does an employer need to write into its own code of conduct?", a: "Its own standard of behaviour, how company property, systems and information may and may not be used, which conflicts of interest must be declared and to whom, and how a breach is raised, investigated and concluded." },
    { q: "Does the code of conduct template say what counts as a breach?", a: "No. What counts as a breach and what follows one are the employer's determinations, set out in the approved document rather than paraphrased on this page." },
    { q: "When is the code of conduct issued to employees in HRMagix?", a: "It is issued to every employee at onboarding and acknowledged per person." },
    { q: "What happens to acknowledgements when the code of conduct is revised?", a: "Acknowledgement is re-opened whenever the text is revised, so each employee confirms the current version rather than an earlier one." },
    { q: "Is a conduct acknowledgement kept after an employee leaves?", a: "Yes. The acknowledgement record survives the employee's exit." },
  ],
  "workplace-harassment": [
    { q: "What does a workplace harassment policy include?", a: "It defines harassment in the workplace, states the obligation it places on every employee, and sets out the route by which someone affected can raise it." },
    { q: "Does the harassment policy cover conduct outside the office?", a: "It applies to conduct at the workplace, at work-related events, and in work-related communication." },
    { q: "Why is a reporting route so important in a harassment policy?", a: "A policy that only defines the offence is half a policy. The reporting route, its confidentiality and the assurance against retaliation are what make it usable by the person who needs it." },
    { q: "What if the complaint is about the person who would normally receive it?", a: "The employer's policy should state who a complaint is made to and what alternative route exists if that person is the subject of it." },
    { q: "What decisions does the employer make in its harassment policy?", a: "What conduct it treats as harassment, who complaints go to and the alternative route, what confidentiality attaches to a complaint and investigation, and what protection against retaliation is guaranteed." },
    { q: "How is this different from the sexual harassment policy?", a: "The sexual harassment policy is held separately because its obligations, timelines and complaints machinery are prescribed by statute rather than chosen by the employer." },
    { q: "How does HRMagix show employees received the harassment policy?", a: "Policy issue and acknowledgement are tracked per employee per version." },
    { q: "Can I see earlier versions of the harassment policy?", a: "Yes. The document vault holds the current text and its revision history." },
  ],
  "sexual-harassment": [
    { q: "Is a sexual harassment policy mandatory for employers in India?", a: "Yes. This is the policy an Indian employer is statutorily required to have, under the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013." },
    { q: "Which law governs the sexual harassment policy?", a: "The POSH Act, 2013 prescribes the employer's obligations, the constitution of the Internal Committee and the redressal process, and the employer's policy document must reflect those requirements." },
    { q: "Who is covered by the sexual harassment policy?", a: "Every person at the workplace, including employees, and, as the statute requires, women engaged at the workplace regardless of employment status." },
    { q: "What must the employer set out about the Internal Committee?", a: "The policy states the constitution of the Internal Committee and who currently sits on it." },
    { q: "What does the policy need to say about filing a complaint?", a: "It sets out how a complaint is filed and within what period, how enquiry proceedings are conducted and concluded, and what interim relief is available while an enquiry is pending." },
    { q: "Why is it separate from the general workplace harassment policy?", a: "Its obligations, timelines and complaints machinery are prescribed by statute rather than chosen by the employer." },
    { q: "How are changes to Internal Committee membership handled in HRMagix?", a: "Committee membership changes are reflected through document versioning." },
    { q: "Is employee acknowledgement of the POSH policy tracked?", a: "Yes. Policy issue and acknowledgement are tracked per employee per version." },
  ],
  "workplace-violence": [
    { q: "What does a workplace violence policy prohibit?", a: "It names the conduct the organisation will not tolerate under any circumstance: threat, intimidation and physical harm." },
    { q: "What makes a workplace violence policy different from other policies?", a: "Its defining feature is speed. It exists so that nobody has to work out who to call while an incident is happening." },
    { q: "Where does the workplace violence policy apply?", a: "To every employee, and to conduct at any company premises or work-related location." },
    { q: "Who should be contacted when a violent incident happens?", a: "The employer's policy states who is contacted immediately and how, so the escalation path is set before an incident occurs." },
    { q: "When is an incident escalated outside the organisation?", a: "That is a decision the employer writes into its own policy, alongside what action follows a substantiated incident." },
    { q: "What decisions does an employer make in this policy?", a: "What conduct is prohibited outright, who is contacted and how, when an incident goes outside the organisation, and what action follows a substantiated incident." },
    { q: "How are escalation contacts kept current in HRMagix?", a: "Current escalation contacts are held in the document vault and versioned." },
    { q: "Does HRMagix record that employees received the violence policy?", a: "Yes. Policy issue and acknowledgement are tracked per employee." },
  ],
  "equal-opportunity": [
    { q: "What does an equal opportunity employer policy commit to?", a: "Non-discrimination across the decisions where discrimination actually occurs: hiring, evaluation, promotion and remuneration." },
    { q: "Why should the policy cover more than hiring?", a: "A commitment stated only at hiring is incomplete. Naming all four decision points makes the commitment checkable at each of them." },
    { q: "Who does the equal opportunity policy apply to?", a: "Every employment decision, and every candidate and employee those decisions touch." },
    { q: "Does the template list the prohibited grounds of discrimination?", a: "No. The grounds on which discrimination is prohibited are one of the decisions the employer writes into its own policy." },
    { q: "What else must the employer define in this policy?", a: "How the commitment applies at each decision point, hiring, evaluation, promotion and pay, and how a concern about a specific decision is raised." },
    { q: "How can a past pay or promotion decision be reviewed for fairness?", a: "Grade, designation and compensation changes are effective-dated on the employee record, so a decision can be reconstructed with the position that applied at the time." },
    { q: "Is acknowledgement of the equal opportunity policy recorded?", a: "Yes. Acknowledgement is tracked per employee." },
    { q: "Which policies should be read with the equal opportunity policy?", a: "The promotion, payment increment and annual performance review policies, since they govern the decisions the commitment applies to." },
  ],
  "open-door": [
    { q: "What is an open door policy?", a: "It gives an employee a route to raise a concern beyond their immediate reporting line, and attaches an assurance to using it." },
    { q: "Why does an organisation need an open door policy?", a: "The ordinary escalation path fails exactly when escalation matters most: when the concern is about the person it would ordinarily be raised with." },
    { q: "Who can use the open door policy?", a: "Every employee, at every grade." },
    { q: "Who can an employee approach under the open door policy?", a: "The employer's policy names who an employee may approach beyond their reporting manager." },
    { q: "What response can an employee expect after raising a concern?", a: "The policy should state what response the employee can expect and in what timeframe, along with what assurance attaches to raising a concern this way." },
    { q: "Are open door conversations recorded in HRMagix?", a: "Where the conversation continues in the platform, 1-on-1 agendas and notes are recorded there." },
    { q: "Is receipt of the open door policy tracked?", a: "Yes. Policy issue and acknowledgement are tracked per employee." },
    { q: "Which policies relate to the open door policy?", a: "The code of conduct and the workplace harassment policy are listed to be read alongside it." },
  ],
  attendance: [
    { q: "What does an attendance policy cover?", a: "How presence is recorded, what counts as a full and a half working day, and how a missed or disputed record is corrected." },
    { q: "Why does payroll depend on the attendance policy?", a: "Pay depends on days present, and almost every payroll dispute in an Indian company traces back to an attendance policy that was either unwritten or applied inconsistently." },
    { q: "Who does the attendance policy apply to?", a: "Every employee whose pay depends on days present, which in practice is everyone, since loss of pay applies at every grade." },
    { q: "Which attendance capture methods can the policy allow?", a: "The employer decides which capture methods are valid for which population: biometric, mobile or browser." },
    { q: "How is a missed punch regularised?", a: "The policy sets how a missed or disputed punch is regularised, who approves it, and by what date in the month requests must be raised. In HRMagix each request carries an approver and a timestamp." },
    { q: "Do biometric, mobile and browser punches end up in one record?", a: "Yes. They settle into one attendance ledger." },
    { q: "How is loss of pay calculated from attendance?", a: "The loss-of-pay register is derived from the same ledger the presence board is drawn from." },
    { q: "Does the template set what counts as a half day?", a: "No. What constitutes a full and a half working day is a threshold the employer sets, and the attendance module then applies it consistently to everyone." },
  ],
  "late-coming": [
    { q: "What does a late coming policy define?", a: "How late arrival is measured against the shift start, how a grace allowance operates where the employer grants one, and what follows from repeated lateness." },
    { q: "Is a late coming policy meant to be punitive?", a: "Its purpose is consistency rather than punishment. A written rule applies identically to everyone, while a manager's judgement does not." },
    { q: "Who does the late coming policy apply to?", a: "Employees working to a defined shift or start time." },
    { q: "Is a grace period mandatory in the late coming policy?", a: "No. Whether a grace allowance is granted, and of what length, is the employer's decision." },
    { q: "How are late marks counted?", a: "The employer sets over what period late marks accumulate and what consequence attaches at each threshold. HRMagix accumulates them against the configured rule rather than a manager's recollection." },
    { q: "How does HRMagix apply the grace period?", a: "Grace periods are configured per policy and applied automatically to every punch." },
    { q: "How is lateness handled for night shifts?", a: "Auto shift detection assigns each punch to the correct shift, including across midnight." },
    { q: "Which HRMagix module enforces the late coming policy?", a: "Attendance & Shifts, where the thresholds are applied by the attendance rules themselves." },
  ],
  leave: [
    { q: "What does a leave policy include?", a: "The leave categories available, how entitlement accrues, how applications are approved, and what happens to a balance at the end of the year." },
    { q: "Which law sets minimum leave entitlements in India?", a: "The applicable state Shops and Establishments Act, or the Factories Act for covered establishments. An employer's policy may be more generous than the statutory floor but not less." },
    { q: "Can one leave policy have different quotas for different states?", a: "Yes. An employer operating in more than one state may need more than one set of quotas under one policy, and quotas may differ by location and grade." },
    { q: "Which leave types can the policy include?", a: "The employer decides which categories exist, such as earned or privilege, casual and sick leave, and any others." },
    { q: "Does the policy cover carry forward and encashment of leave?", a: "Yes. The employer defines whether unused leave carries forward, up to what cap, and whether it is encashable." },
    { q: "Is the sandwich rule part of the leave policy?", a: "The employer states whether and how the sandwich rule is applied, if it applies it at all." },
    { q: "Why do employees, managers and payroll see the same leave balance?", a: "HRMagix computes balances from the accrual rule rather than storing them, so every view shows the same number." },
    { q: "How does unpaid leave affect salary in HRMagix?", a: "Unpaid days flow directly into the month's payable-days figure." },
  ],
  "maternity-leave": [
    { q: "Which law governs maternity leave in India?", a: "The Maternity Benefit Act, 1961 (as amended) prescribes the minimum entitlement, notice and benefit obligations, and the employer's policy must reflect at least those requirements." },
    { q: "What does a maternity leave policy cover?", a: "Maternity entitlement, how it is notified and approved, and how the period of absence is treated in relation to continuous service and benefits." },
    { q: "Why is maternity leave a separate policy from general leave?", a: "Its entitlement is statutory rather than discretionary, and the treatment of service during the absence has consequences that ordinary leave does not." },
    { q: "Can an employer offer more than the statutory maternity entitlement?", a: "The employer's policy states the entitlement it provides and how it relates to the statutory minimum, which it must at least meet." },
    { q: "How does an employee notify the employer of maternity leave?", a: "How and when the employee notifies the organisation is defined in the employer's own policy." },
    { q: "Does maternity leave count towards continuous service?", a: "The policy defines how the period is treated for continuous service, accrual and benefits. HRMagix tracks it against the employee record so continuous service is computed correctly for gratuity." },
    { q: "How is maternity leave set up in HRMagix?", a: "It is configured as its own leave category with its own entitlement and approval path." },
    { q: "Does the policy address returning to work?", a: "Yes. The employer defines what arrangements apply on return." },
  ],
  "work-from-home": [
    { q: "What does a work from home policy cover?", a: "When remote working is available, how it is requested and approved, and which obligations continue to apply while working away from an office." },
    { q: "Who is eligible to work from home?", a: "Employees in roles the employer designates as eligible, with the eligible roles or grades and the basis stated in the policy." },
    { q: "Which obligations still apply when working from home?", a: "The employer lists which obligations continue unchanged, such as availability, confidentiality and attendance recording. This clause prevents most remote-working disputes." },
    { q: "How is a work from home day requested?", a: "The employer's policy sets how a remote day or period is requested and approved." },
    { q: "Does the policy cover equipment and internet for remote work?", a: "Yes. The employer defines what equipment and connectivity arrangements apply." },
    { q: "How is attendance marked for remote employees in HRMagix?", a: "Browser and mobile check-in record attendance without a geofence where none applies." },
    { q: "Can the team see who is working from home?", a: "Approved remote days are visible on the shared team calendar." },
    { q: "Which policies should be read with the work from home policy?", a: "The work from home monitoring policy, the work from home exclusivity policy and the attendance policy." },
  ],
  "work-from-home-monitoring": [
    { q: "What does a work from home monitoring policy state?", a: "What is recorded while an employee works remotely, how that record is used, and the limits placed on it." },
    { q: "Why state the limits of monitoring in the policy?", a: "A monitoring policy that only describes what is captured invites suspicion. Stating the limits and permitted uses makes remote working workable for both sides." },
    { q: "Who does the monitoring policy apply to?", a: "Employees working remotely under the work-from-home policy." },
    { q: "Who can access remote working records?", a: "The employer defines who may access them and for what purposes. In HRMagix, access to attendance and location data is governed by role-based permissions." },
    { q: "How long are remote monitoring records kept?", a: "Retention is one of the decisions the employer writes into its own policy." },
    { q: "What is HRMagix attendance capture used for during remote work?", a: "It is scoped to establishing payable days and reconciling leave." },
    { q: "Does HRMagix use geo-fencing or selfies for remote employees?", a: "Only where the employer configures them for a specific site." },
    { q: "Does the policy say what records will not be used for?", a: "Yes. The employer states what is not recorded and what the records will not be used for." },
  ],
  "work-from-home-exclusivity": [
    { q: "What is a work from home exclusivity policy?", a: "It states the expectation that time recorded as working is worked exclusively for the employer, and how concurrent engagements are treated." },
    { q: "Why is an exclusivity policy needed for remote work?", a: "Remote working removes the incidental visibility an office provides, so the expectation has to be written down rather than assumed." },
    { q: "Who does the exclusivity policy apply to?", a: "Employees working remotely, and any employee with an outside engagement." },
    { q: "Can employees take on outside work under this policy?", a: "The employer decides whether outside engagements are permitted, and under what declaration or approval." },
    { q: "How is a conflict with an outside engagement resolved?", a: "The employer's policy defines how a conflict is identified and resolved." },
    { q: "Does the template define what exclusivity means?", a: "No. What exclusivity means is stated in the employer's own terms." },
    { q: "Where are outside engagement declarations stored in HRMagix?", a: "Declarations are filed against the employee record in the document vault." },
    { q: "Is acknowledgement of the exclusivity policy tracked?", a: "Yes. Acknowledgement is tracked per employee per version." },
  ],
  "time-and-work-tracking-software": [
    { q: "What does a time and work tracking software policy cover?", a: "The employee's obligations in relation to the systems used to record time and work, and how the resulting records are treated." },
    { q: "What is the main concern of this policy?", a: "The integrity of the record itself: that punches are the employee's own, that regularisations are truthful, and that the data is what payroll relies on." },
    { q: "Who does the tracking software policy apply to?", a: "Every employee whose time is recorded in a company system." },
    { q: "Can an employee mark attendance for a colleague?", a: "The policy sets out the employee's obligation to record accurately and not on another's behalf, and what follows from a falsified record." },
    { q: "Which systems count as the system of record?", a: "The employer names which systems are the systems of record in its own policy." },
    { q: "Can HRMagix show where a punch came from?", a: "Yes. Every punch carries its source: biometric device, mobile app or browser." },
    { q: "Does HRMagix support location and selfie checks on mobile?", a: "Mobile check-ins can carry location tagging and selfie validation where configured." },
    { q: "Are regularisation requests auditable?", a: "Yes. Regularisations record who requested and who approved." },
  ],
  "probationary-period": [
    { q: "What does a probationary period policy cover?", a: "The purpose and duration of probation, how performance is assessed during it, and how confirmation, or its refusal, is communicated." },
    { q: "Why must probation end with an explicit decision?", a: "A probation period that ends without one leaves both sides unclear about the employee's status, which becomes a problem precisely when it matters." },
    { q: "Who does the probation policy apply to?", a: "Employees serving an initial probationary period." },
    { q: "Can probation be extended?", a: "The employer's policy states the length of probation and whether it may be extended." },
    { q: "Who assesses an employee during probation?", a: "The policy defines how performance is assessed during the period and by whom." },
    { q: "Do notice, leave and benefits differ during probation?", a: "The employer states which terms differ during probation, such as notice, leave and benefits." },
    { q: "How does HRMagix stop probation end dates being missed?", a: "Probation end dates surface to the reporting manager ahead of time rather than after." },
    { q: "What happens in HRMagix when an employee is confirmed?", a: "Confirmation is an effective-dated change on the employee record, so downstream terms follow automatically." },
  ],
  "annual-performance-review": [
    { q: "What does an annual performance review policy include?", a: "The review cycle, who participates in an assessment, how ratings are calibrated across managers, and how outcomes are recorded and communicated." },
    { q: "Why is calibration important in performance reviews?", a: "Without it, a rating means something different under each manager, and every downstream decision inherits that inconsistency." },
    { q: "Who is covered by the performance review policy?", a: "Employees eligible for review under the cycle the employer defines." },
    { q: "Who can contribute to a performance assessment?", a: "The employer decides who contributes, for example self, manager, peers and skip-level." },
    { q: "Can employees appeal a review outcome?", a: "The policy defines how the outcome is recorded, communicated and appealed." },
    { q: "Does the template set a rating scale or review dates?", a: "No. The cycle, its dates and any rating scale are the employer's criteria, stated in the approved document." },
    { q: "How does HRMagix keep reviews based on the whole period?", a: "OKRs and KRAs carry live progress through the period, so a review references the quarter rather than a recollection of it." },
    { q: "Does HRMagix support 9-box and calibration views?", a: "Yes. The 9-box talent matrix and calibration views read the same underlying data." },
  ],
  promotion: [
    { q: "What does an employee promotion policy state?", a: "The basis on which a promotion is considered, who decides, and how a change in grade or designation takes effect." },
    { q: "Why write down the basis for promotion?", a: "It makes progression legible. Where the basis is unwritten, the absence of a promotion is read as a judgement about the person rather than about the criteria." },
    { q: "Who is covered by the promotion policy?", a: "Every employee eligible for progression under the employer's grade structure." },
    { q: "Who approves a promotion?", a: "The employer's policy defines who proposes, who reviews and who approves." },
    { q: "Are promotions tied to the performance review cycle?", a: "How the decision relates to the review cycle is something the employer defines in its policy." },
    { q: "When does a promotion take effect?", a: "The policy states from what date a promotion takes effect and how it is communicated." },
    { q: "Can past grades and designations be looked up in HRMagix?", a: "Yes. Changes are effective-dated rather than overwritten, so the position that applied at any past date remains reconstructable." },
    { q: "Does a promotion need to be entered separately in payroll?", a: "No. The change reaches the next payroll run without a second entry." },
  ],
  "payment-increment": [
    { q: "What does a payment increment policy cover?", a: "The circumstances in which compensation is reviewed, the basis on which a revision is decided, and when a revision takes effect." },
    { q: "Why does the effective date of a salary revision matter?", a: "A revision agreed in one month and effective in another has arrears consequences that need to be settled by policy rather than case by case." },
    { q: "Who does the increment policy apply to?", a: "Every employee whose compensation is subject to review." },
    { q: "How often is salary reviewed under this policy?", a: "When compensation is reviewed, and on what cycle, is set by the employer in its own policy." },
    { q: "How are salary arrears handled in HRMagix?", a: "Arrears are handled as a payroll component within the run. The policy defines how arrears are treated where the effective date precedes the decision." },
    { q: "Does a mid-year increment change earlier payroll months?", a: "No. Salary structures are effective-dated, so a mid-year revision does not rewrite the months before it." },
    { q: "Which salary structure applies when rerunning a past month?", a: "A payroll run for a past month uses the structure that was in force in that month." },
    { q: "What decisions does the employer make in the increment policy?", a: "The review cycle, what the revision is based on, the date a revision takes effect, and how arrears are treated." },
  ],
  "timely-submission-of-reports": [
    { q: "What does a timely submission of reports policy cover?", a: "The reporting obligations attached to a role, the expectation of timeliness, and what follows from persistent delay." },
    { q: "Why have a policy on report deadlines?", a: "Reporting deadlines are usually the first obligation to slip and the last to be addressed, and downstream work, including payroll cutoff, depends on them." },
    { q: "Who does this policy apply to?", a: "Employees in roles carrying a defined reporting obligation." },
    { q: "Which reports does the policy include?", a: "The employer defines which reports are due, from whom, and to whom." },
    { q: "How do report deadlines relate to payroll cutoff?", a: "The policy sets the deadline for each report and how it relates to the payroll cutoff." },
    { q: "Can an employee get an extension on a report?", a: "The employer's policy states how an extension is requested." },
    { q: "How does HRMagix track report deadlines?", a: "Reminders and document deadlines are tracked rather than remembered." },
    { q: "Is there a record of when reports were submitted?", a: "Yes. Approval and submission actions leave a dated trail." },
  ],
  gratuity: [
    { q: "When does gratuity become payable in India?", a: "Under the Payment of Gratuity Act, 1972, gratuity becomes payable on completing five years of continuous service. The Act also prescribes circumstances in which the five-year condition does not apply." },
    { q: "How is gratuity calculated?", a: "At fifteen days of last drawn wages for each completed year of service, on a twenty-six day divisor, as prescribed by the Payment of Gratuity Act, 1972." },
    { q: "What does a gratuity policy add to the law?", a: "It is largely a restatement of the law plus the organisation's own administrative process, including how a claim is administered and within what period it is settled." },
    { q: "Can an employer pay more than statutory gratuity?", a: "Whether the organisation provides above the statutory formula is one of the decisions written into its own policy." },
    { q: "How is continuous service counted after a break?", a: "The employer's policy defines how continuous service is computed where there has been a break." },
    { q: "Why provision for gratuity before it is due?", a: "Provisioning recognises the liability before it falls due. In HRMagix it runs before eligibility is reached, so the liability is visible rather than sudden." },
    { q: "How is gratuity settled on exit in HRMagix?", a: "Settlement is computed from the same attendance and salary history the rest of payroll uses." },
    { q: "Is there a gratuity calculator on this site?", a: "Yes. The gratuity calculator applies the statutory formula to figures you enter." },
  ],
  "employee-resignation": [
    { q: "What does an employee resignation policy cover?", a: "How a resignation is tendered and acknowledged, and the sequence of clearance, handover and settlement that follows it." },
    { q: "Why set out the resignation process in advance?", a: "An exit generates more obligations than a joining. A set sequence lets a departure be handled without improvisation when goodwill is already thin." },
    { q: "How and to whom should a resignation be submitted?", a: "The employer's policy states how a resignation is tendered, to whom, and within what period it is acknowledged." },
    { q: "What handover is expected when resigning?", a: "The policy defines the handover expected and to whom it is given." },
    { q: "How does exit clearance work in HRMagix?", a: "Clearance and asset recovery run as a checklist against the employee record, with the sign-off sequence across departments defined in the policy." },
    { q: "How is full-and-final settlement calculated?", a: "It is computed from the same attendance and leave ledger used all year. When it is paid is defined in the employer's policy." },
    { q: "Can a former employee still get documents after leaving?", a: "Yes. Documents are retained after the login closes, so a letter can still be issued later." },
    { q: "Which policies apply alongside resignation?", a: "The notice period, notice period buyout and gratuity policies are read alongside it." },
  ],
  "notice-period": [
    { q: "What does a notice period policy cover?", a: "The notice obligation on each side, how notice is served, and how it interacts with leave and the final working day." },
    { q: "Does the notice period apply to the employer too?", a: "Yes. It applies to both parties: the employee resigning and the employer terminating." },
    { q: "Can the notice period differ by grade or during probation?", a: "The employer defines the notice required from each side and whether it varies by grade or probation status." },
    { q: "Can leave be taken or encashed during the notice period?", a: "That is where most disputes arise, so the employer's policy settles whether leave may be taken or encashed during notice." },
    { q: "How is the last working day determined?", a: "The policy defines how the last working day is determined, including from what date notice runs." },
    { q: "Does the template state a notice period?", a: "No. The notice period is a term the employer sets, quoted from its approved document rather than summarised here." },
    { q: "How does HRMagix use notice dates?", a: "Notice dates are held on the employee record and drive the final settlement calculation." },
    { q: "How is leave during notice handled in HRMagix?", a: "Leave taken during notice is applied through the same leave scheme as any other period." },
  ],
  "notice-period-buyout": [
    { q: "What is a notice period buyout policy?", a: "It states when notice may be bought out rather than served, who may agree to it, and how the amount is treated in the final settlement." },
    { q: "Why have a written notice buyout policy?", a: "So that a buyout is a defined commercial option rather than a negotiation conducted under time pressure by whoever is handling the exit." },
    { q: "Who does the buyout policy apply to?", a: "Employees seeking to shorten a notice period by agreement." },
    { q: "Can either side buy out the notice period?", a: "The employer's policy states whether buyout is permitted, and in which direction." },
    { q: "How is the notice buyout amount calculated?", a: "The calculation is defined in the employer's policy, along with who has authority to agree to it." },
    { q: "How is a buyout taxed?", a: "The policy states how the amount is treated in the full-and-final settlement, including its tax treatment." },
    { q: "Is a buyout processed through payroll in HRMagix?", a: "Yes. Buyout is handled as a component within the final settlement rather than outside payroll." },
    { q: "Can the buyout calculation be checked later?", a: "Yes. The settlement working is retained and reconstructable." },
  ],
  "employee-termination": [
    { q: "What does an employee termination policy cover?", a: "The grounds and process for termination by the employer, including the procedural steps that must precede it." },
    { q: "Why is process so important in termination?", a: "Termination without a documented process is difficult to defend, and the documentation has to be created at the time rather than assembled afterwards." },
    { q: "What steps should come before a termination decision?", a: "The employer defines them, for example notice of concern, an opportunity to respond, and an enquiry where required." },
    { q: "Who can decide to terminate an employee?", a: "The policy states who decides and at what level of authority." },
    { q: "Does the policy cover notice or pay in lieu on termination?", a: "Yes. The employer defines what notice or payment in lieu applies." },
    { q: "Who does the termination policy apply to?", a: "Every employee, and every termination initiated by the employer." },
    { q: "What records support a termination in HRMagix?", a: "Performance history, review outcomes and improvement plans are recorded with their dates." },
    { q: "Can the employee's position at each step be reconstructed?", a: "Yes. The employee record is versioned, so the position at each step remains reconstructable." },
  ],
  "employee-absconding": [
    { q: "What is an employee absconding policy?", a: "It states how unexplained absence is treated, what attempts at contact must be made, and the point at which employment is deemed to have ended." },
    { q: "Why does a company need an absconding policy?", a: "Without it, an unexplained absence has no defined end point, and the employee remains on the books indefinitely." },
    { q: "Who does the absconding policy apply to?", a: "Employees absent without approved leave or intimation." },
    { q: "After how many days is an employee treated as absconding?", a: "The number of days of unexplained absence that triggers the policy is set by the employer in its own document." },
    { q: "What contact attempts are required before ending employment?", a: "The policy defines what attempts must be made, through which channels, and over what period." },
    { q: "How is final settlement handled for an absconding employee?", a: "The employer's policy sets how the final settlement and any recoveries are handled." },
    { q: "When does HRMagix show unexplained absence?", a: "It is visible in the attendance ledger from the first day, not at month end." },
    { q: "Are contact attempts recorded in HRMagix?", a: "Yes. Contact attempts and notices are filed against the employee record with their dates." },
  ],
};
